### ISSUE TITLE
Provide support for has() ANDing and ORing.

### ISSUE THREAD

**Issue by okram** [tinkerpop/tinkerpop3#130]
By TP3 GA we should have support for ANDing and ORing on has() steps (and ultimately, via propagation to XXXGraphStep, support for complex index lookups).

Currently we can do this:

```groovy
g.V.has('name','marko').has('age',T.lt,34)  // chaining ANDs
g.V.has('name', Contains.IN, ['marko','daniel'])  // ORing on a single property
```

We need to support arbitrary ANDing and ORing. Is the following proposal sufficient?

```groovy
g.V.has('name','marko',T.or,'age',T.lt,34)  // name = marko || age < 34
g.V.has('name','marko').has('age',T.lt,34,T.or,'weight',T.lt,150)  // name = marko && (age < 34 || weight < 150)
```

In the above model, `has(Object...)` which is not good from an API standpoint and the parsing would be lots of `if(object[i] instanceof BiPredicate)`, `if(object[i] instanceof Or)` to generate the HasContainers. The HasContainers would then need to be represented in a nested list to expose the clauses.

However, is the above proposal sufficient? What about `(name = marko && age < 34) || (name = daniel && weight < 150)`, where chaining is an OR, not an AND.

```groovy
g.V.has('name','marko',T.and,'age',T.lt,34).orHas('name','daniel',T.and,'weight',T.lt,150)
```

In this model, each `has()` is a clause. and you can either `andHas()` or `orHas()` clauses together, where `andHas()` can simply call `has()`, but is provided so chaining predicate is obvious. 

How would you interpret the following expression?

```groovy
g.V.has('label','person')
     .andHas('name','marko',T.and,'age',T.lt,34)
     .orHas('name','daniel',T.and,'weight',T.lt,150).blah()
==>
(label = person) AND ((name = marko AND age < 34) OR (name = daniel AND weight < 150))
```

The problem here is then can Daniel not be a person? To which I would say "no". The first `has()` checks if the element is a person. The next checks if the element is `name=marko AND age < 34`. If the `andHas()` is true, the traverser jumps to `blah()` else it goes through `orHas()` which is simply a predicate check like any old `has()`. The "jump" is what simulates the 'or'. 

If you don't care if Daniel is a "person" then you do:

```groovy
g.V.has(Element.LABEL,'person',T.and,'name','marko',T.and,'age',T.lt,34)
     .orHas(T.and,'name','daniel',T.and,'weight',T.lt,150)
==>
(label = person AND name = marko AND age < 34) OR (name = daniel AND weight < 150)
```

How do you do more complex nestings?

```groovy
g.V.has('name','marko').orHas('name','daniel').andHas('age',T.lt,34).orHas('weight',T.lt,150).blah()
==>
g.V.has('name','marko').orHas('name','daniel').andHas('age',T.lt,34,T.or,'weight',T.lt,150).blah()
==>
name = marko OR (name = daniel AND (age < 34 OR weight < 150))
```

. Is the name marko? If so, you are done and jump to `blah()`.
. Is the name daniel? If so, continue, else kill traverser.
. Is the age of daniel < 34? If so, jump to `blah()`.
. Is the weight of daniel < 150? If so, continue, else kill the traverser.

In essence, each `orHas()` and `andHas()` generates a new clause. However, I don't believe this is fully generic.

I'm not happy with any of this right now so other proposals are greatly appreciated.
  @dkuppitz @mbroecheler @rjbriody @pietermartin @spmallette @joshsh

**Comment by rjbriody** [comment]
It seems important to ensure that we can support DNF queries of simple has constrains in a single index call. @mbroecheler, maybe query optimizers will be able to do that with union and match step? If not, then we may want to consider making OR'ing of simple has constraints a special case. For example: "Get vertices where 'firstName' is 'Bob' OR 'lastName' is 'Briody'", should become a single index call.

**Comment by mbroecheler** [comment]
@okram Why is this issue closed? I don't see how step modulators allow us to build general logical formula - the issue remains: building such formula in a fluid API leads to a very awkward API.

@rjbriody Yes, this will eventually be addressed in match step once we figure out how to create the API for it. Building a query optimizer for union step will be too cumbersome.

**Comment by okram** [comment]
This issue is not closed. The step modulators issue is closed which is referenced by this ticket. ?

**Comment by okram** [comment]
With all the new work on step-modulators, traversal lambdas, and the like, is there anything new that can be said on this front?

**Comment by okram** [comment]
Here is a trip of an idea. Imagine the following new methods on `GraphTraversal`.

```java
public GraphTraversal<S,E> and();
public GraphTraversal<S,E> or()
public GraphTraversal<S,E> and(Traversal<E,?>... traversals)
public GraphTraversal<S,E> or(Traversal<E,?>... traversals)
```

Now you can do this:

```groovy
g.V.has(__.outE.count.is(gt,2).or.inE.count.is(lt,5)).name
```

Perhaps written using the following convention (if you want):

```groovy
g.V.has(__.outE.count.is(gt,2).
               or.
           inE.count.is(lt,5)).name
```

The above are equivalent to:

```groovy
g.V.has(__.or(__.outE.count.is(gt,2), __.inE.count.is(lt,5))).name
```

A strategy will provide the rewrite. Its a really easy rewrite.

Now, lets get crazy:

```groovy
g.V.has(__.outE.count.is(gt,2).
                     or(__.inE.count.is(lt,5).
                       and(__.age.is(25).
                                     or.
                                   age.is(gt,50))).name
```

This is equivalent to:

```groovy
g.V.has(__.outE.count.is(gt,2).or(__.inE.count.is(lt,5), __.has(__or(__.age.is(25),__.age.is(gt,50))))).name
```

In short, this model allows writing your conjunction in the familiar "X and Y" form OR, if you wish, in the first order logic form of "and(x,y)". Ultimately, there is a rewrite to the first order logic form, but arguably, its nicer for the user to use the "X and Y" form and only use parentheses when they need nesting.

All we would need is `AndStep` and `OrStep` which `branch/` steps similar to `union()`.

Finally, not using `has(traversal)`.

```groovy
g.V.count.is(gt,6).or.outE.count.is(lt,30)
```

Equivalent to:

```groovy
g.V.or(__.count.is(gt,6), __.outE.count.is(lt,30))
```

Which, of course is a `Traversal<Vertex,Boolean>`.

**Comment by okram** [comment]
Oh yea, and realize that in Groovy you don't need the `.` (its assumed with a space). Thus:

```groovy
g.V.has(__.outE.count.is(gt,2) or inE.count.is(lt,5)).name
```

Next, in Groovy, you can make `__` be the "default object" and thus:

```groovy
g.V.has( outE.count.is(gt,2) or inE.count.is(lt,5) ).name
```

Finally, you can override operators such that `Traversal > Object` can be defined as `Traversal.is(gt,object)` Leading to:

```groovy
g.V.has( outE.count > 2 or inE.count < 5 ).name
```

Eh.?

**Comment by okram** [comment]
Lets do the more complicated example of:

```groovy
g.V.has(__.outE.count.is(gt,2).
                     or(__.inE.count.is(lt,5).
                       and(__.age.is(25).
                                     or.
                                   age.is(gt,50))).name
```

...using Groovy DSL magic.

```groovy
g.V.has(outE.count > 2 or(inE.count < 5 and(age == 25 or age > 50))).name
```

Pretty, no?

**Comment by dkuppitz** [comment]
Well, the last Groovy sample looks nice. I guess you've already implemented everything locally, so, yea - push it. But don't be disappointed if nobody uses ```and()``` or ```or()``` :).

Just to show why I don't like it. Here's your last complex example using the steps we already have:

```java
g.V().has(__.union(__outE().count().is(gt, 2),
                   __.has(__.inE().count().is(lt, 5L)).
                      has(__.values("age").union(__.is(25), __.is(gt, 50))))).values("name")
```

In short: ```and()``` can be accomplished by chaining multiple ```has()``` steps, ```or()``` by using ```union()```.

Unfortunately, all you get from the aforementioned traversal is an exception:

> Global nested traversals may not contain barrier-steps [VertexStep(OUT,edge), CountStep, IsStep(2), EndStep]

But anyway, it's the same thing. So if you know how to use barrier steps within ```and()``` and ```or()```, then it should also be possible within ```union()```.

**Comment by pietermartin** [comment]
I am currently working on a gremlin compiler/parser/optimizer for sqlg.
Primarily to turn consecutive `in` `out` `has` into as few queries as possible. (later I'll try include `as`). 

This is going well so far except for that `or` is excluded from this party. And its a large exclusion.

So the problem with the `union` solution (for me at least) is that it will be very difficult to optimize it. As the union step can contain almost anything it is hard to synchronize the 2 queries into one or few calls to the back end.

This is critical as for any non embedded db, remote calls are a performance killer.

@okram can you show how the following query will look with the the `and` and `or`
```
g.V().has(T.label, 'Person') -> where name = 'john' or gender = 'female'
```

**Comment by dkuppitz** [comment]
> So the problem with the union solution (for me at least) is that it will be very difficult to optimize it.

So? Why is it easier when ```or()``` is used instead of ```union()```? The samples above show that ```or()``` can take an arbitrary traversal just as ```union()```.

Your query:

```groovy
g.V().has(T.label, 'Person').union(__.has('name', 'john'), __.has('gender', 'female'))

// or

g.V().has(T.label, 'Person').or(__.has('name', 'john'), __.has('gender', 'female'))

// or (with a lot of groovy magic), although that's irrelevant for your sqlg project

g.V().has(T.label, 'Person').has(name == 'john' or gender == 'female')
```

**Comment by pietermartin** [comment]
Yes indeed, was just wanting to check that I understood it correctly.
Afraid I do not have any positive input to give for solving my own problem.

**Comment by okram** [comment]
@pietermartin 

You asked for the following query using the proposed `and()` `or()` model.

```groovy
g.V().has(T.label, 'Person') -> where name = 'john' or gender = 'female'
```

Converted:

```groovy
g.V().has(label,'Person').and(__.has('name','john').or().has('gender','female'))) // Gremlin-Java
g.V().has(label,'Person') and (has('name','john') or has('gender','female'))) // Gremlin-Groovy, no sugar.
g.V.has(label == 'person' and (name == 'john' or gender == 'female')) // Gremlin-Groovy with proposed sugar extensions
```

The problem I just ran into is that Groovy doesn't let you overload `>`, `<`, `==`, etc. operators. Thus, it would look like this with comparators:

```groovy
g.V.has(label == 'person' and (name == 'john' or age gt 45))
```

The GraphTraversalCategory (i.e. Groovy trait) would have `gt`, `lt`, etc. defined for the conversion.

**Comment by mbroecheler** [comment]
I find this really hard to read, because you think of it as one traversal:
```java
g.V.count.is(gt,6).or.outE.count.is(lt,30)
```

What I mean is this: The beauty of (basic) gremlin is that you can read the expression from left to right and concatenate the pipelines in your head: "We start with the graph, get its vertices, of those only the ones with name='Marko', then grab their out edges...". That makes Gremlin easy to read and parse for a human being which I believe to be the most important aspect of a query language - even more important than expressive power.

Now, throwing in an 'or' in the middle trips people up because you suddenly have to jump back in the pipeline and figure out where this break applies.

This reads a lot better but relies on line breaks and indentation which is often not available in a query UI:
```java
g.V.has(__.outE.count.is(gt,2).
                     or(__.inE.count.is(lt,5).
                       and(__.age.is(25).
                                     or.
                                   age.is(gt,50))).name
```

In groovy (sugar), we could do:
```groovy
g.V.has( outE.count > 2 || ( inE.count < 5 && ( age == 25 || age == 50))).name
```

which I think would be much preferable for the human eye. So, I guess what I am trying to argue for is: Let's use polish notation in Java and "standard" boolean notation in groovy sugar.

**Comment by okram** [comment]
@mbroecheler You get `&&` and `||` for free as the Groovy overload methods are `and()` and `or()`. http://groovy.codehaus.org/Operator+Overloading

**Comment by rjbriody** [comment]
```g.V().has(label,'Person').and(__.has('name','john').or().has('gender','female'))) // Gremlin-Java```

Could something like this be optimized to a single index hit?

**Comment by mbroecheler** [comment]
@rjbriody Technically, it could but if each vendor has to write code to deconstruct such nested traversals it'll get ugly. We should provide have a syntax-tree representation in TinkerPop for this.

**Comment by pietermartin** [comment]
A syntax tree representation would be very very nice.

**Comment by okram** [comment]
This ticket is done.

`AndStep` and `OrStep` now exist and they support prefix and infix notation. They both extend `ConjunctionStep`. There is a corresponding `ConjunctionStrategy` that rewrites infix notation to the ultimate prefix form. In terms of syntax tree representation (@mbroecheler and @pietermartin), right now you can walk the `ConjunctionStep`-tree, but it will be nasty for vendors having to inspect each step in the tree and be like: "is this a HasStep? yes, okay, give me your has container...". We can add:

```java
List<Conjunction,List> hasContainers = conjunectionStep.getHasContainers()
```

This would return something like:

```js
[
  and : [ 
    has[name,eq,'marko'],
    or : [
      and : [ 
          has[age,gt,30], 
          has[label,eq,person]
      ],
    ],
  ],
]
```

Finally, thoughts are needed on if the conjunction more than just `has()`-containers... perhaps like `LocalStep.isLocalStarGraph()` we could have `ConjunctionStep.isPurelyHasSteps()`. If not, most vendors will just execute without doing a `HasContainer`-fold. Vendors like Titan will already let the users know this with the `[WARNING] Serial scan of the vertices taking place...`. I will make this last part a new ticket.

**Comment by pietermartin** [comment]
Great tx, look forward to implementing it.
