### ISSUE TITLE
Improve gremlin.bat

### ISSUE THREAD

**Issue by Zuela** [tinkerpop/tinkerpop3#15]
Attempting to add TP3 onto Windows, but only able to find gremlin.sh / gremlin-server.sh. Apologies if non-issue!

**Comment by spmallette** [comment]
made some changes and tested on windows - both `gremlin-server.bat` and `gremlin.bat` are working about as well as i can get them.  they behave just as their `.sh` counterparts, with some minor pathing inconsistencies that we've always have had and can't seem to get rid of.  Given that we've made several requests for help on improving the `.bat` stuff and have not gotten any response, I think we should just close this one at this point.  It should be good enough for GA at this point.
