### ISSUE TITLE
Enable .profile()-step unit tests

### ISSUE THREAD

**Issue by rjbriody** [tinkerpop/tinkerpop3#268]
The .profile()-step tests are currently disabled because profiling can only be enabled via System property at start-up time. Need to find a workaround for this.

Also need to ensure coverage for all steps that have profiling logic.

**Comment by okram** [comment]
Where are we on this ticket?

**Comment by rjbriody** [comment]
This was completed a while ago when I finished the new profiling implementation. I missed this ticket.
