### ISSUE TITLE
Another overload for .has()

### ISSUE THREAD

**Issue by dkuppitz** [tinkerpop/tinkerpop3#27]
It would be nice if ```.has()``` would have an overload that accepts a traversal.

For example, to get the edge between two vertices, you can currently do:

```groovy
g.v(1).outE().as('x').inV().retain(g.v(2)).back('x')
// or
g.v(1).outE().filter({ it.get().inV().retain(g.v(2)).hasNext() })
```

But this would be much more readable:

```groovy
g.v(1).outE().has(g.of().inV().retain(g.v(2)))
```

In this case ```.has()``` behaves like ```.and()``` and ```.or()``` in Gremlin2, but with a single condition.

**Comment by okram** [comment]
This is fully doable and easy now that we don't have to linearize steps. Here is the thing though, it will have to exhaust the entire traversal in `has(traversal)` and not just be a `hasNext()` so the semantics are consistent between OLTP and OLAP.

In OLTP, it doesn't require history as we can just hold the object to filter (i.e. the object prior to `has()`) in memory. In OLTP, we don't have that luxury so we will need the path history. 

Finally, I think we should get rid of `back()` if we do this.... ? .... has()-OLTP is faster than back()-OLTP. And equivalent in the OLAP case. Thoughts?

**Comment by okram** [comment]
Actually, this is not possible in OLAP............................. unless we assume that the "has" is local (can't leave the local vertex star. weird...... huh..... The problem is that we don't know which traversers are part of the original "has-calling" traverser. Thus, what to filter? Maybe based on the path information (but then, there could have been two back to back traversers of the same type)... weird.

**Comment by dkuppitz** [comment]
> Finally, I think we should get rid of  ```back()```  if we do this.... ?

No, it's still needed.

```groovy
g.V().out().as("x").out("foo").store("y").back("x").out("bar").except("y")
```

You don't want to rewrite that query using ```.has()```, it would look odd.

Wrote this

**Comment by dkuppitz** [comment]
I would say ```.has()``` is in fact local. Why do you think it's not? Example?

**Comment by okram** [comment]
"local" meaning you can't leave the "star graph of the vertex"... i.e. `g.V().has(__.out().has('key'))` is not allowed as you leave the vertex-space with `out()`. -- OLAP.
