### ISSUE TITLE
Traversal.reverse()

### ISSUE THREAD

**Issue by mbroecheler** [tinkerpop/tinkerpop3#326]
currently calls reverse() on each step. While that has the right semantics in some cases, i.e.

```java
v.outE('knows').has('weight',5).inV
```
gets reversed to:

```java
v.inE('knows').has('weight',5).outV
```

More complex traversals don't get reversed correctly:

```java
v.outE('knows').has('weight',5).inV.outE('married').interval('since',0,10).inV
```

becomes
```java
v.inE('knows').has('weight',5).outV.inE('married').interval('since',0,10).outV
```
whereas the "married" and "knows" should be flipped. Hence, more thought needs to be given to traversal reversal in the general case.

**Comment by okram** [comment]
For GA we should remove "reverse()" concept and come back to it later. Will remove.

**Comment by okram** [comment]
Gutted `Reversible` interface. Will readdress this post GA.

**Comment by mbroecheler** [comment]
Isn't this needed in MatchStep implementation? How is this being addressed
in the meantime?

On Mon, Mar 16, 2015 at 9:32 AM, Marko A. Rodriguez <
notifications@github.com> wrote:

> Gutted Reversible interface. Will readdress this post GA.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tinkerpop/tinkerpop3/issues/326#issuecomment-81779030>
> .
>



-- 
Matthias Broecheler
http://www.matthiasb.com

**Comment by okram** [comment]
MatchStep doesn't use it. Its one of the features that @joshsh has on his "wish list" for MatchStep.

**Comment by mbroecheler** [comment]
Titan uses: ((VertexStep) startStep).reverse();
Can that stay?

On Tue, Mar 17, 2015 at 12:09 PM, Marko A. Rodriguez <
notifications@github.com> wrote:

> MatchStep doesn't use it. Its one of the features that @joshsh
> <https://github.com/joshsh> has on his "wish list" for MatchStep.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tinkerpop/tinkerpop3/issues/326#issuecomment-82539439>
> .
>



-- 
Matthias Broecheler
http://www.matthiasb.com

**Comment by okram** [comment]
In `VertexProgramHelper` we have "reverse()" which is super simple to reverse outE -> inE, outV -> inV....  That is for MessageScope.

For `((VertexStep)startStep).reverse()`, we have have a new method  `((VertexStep)startStep).reverseDirection()`...
