### ISSUE TITLE
Consider VertexProperty cardinality

### ISSUE THREAD

**Issue by rjbriody** [tinkerpop/tinkerpop3#389]
As of right now, a VertexProperty can always have multiple values, and each of those properties can have meta-properties. I'm wondering if there are use cases that could be made more simple by having a VertexProperty take a cardinality to signify ```SINGLE``` vs ```MULTI```, and maybe even ```META```.

Thoughts?

**Comment by okram** [comment]
I still think this is a good idea. Any thoughts? @dkuppitz @spmallette @mbroecheler 

https://github.com/tinkerpop/tinkerpop3/issues/389#issuecomment-67645613

**Comment by dkuppitz** [comment]
I like your the suggestions regarding the method signatures. What I don't like is that ```multi``` is the default (the default use case is most likely ```single```).

**Comment by okram** [comment]
I would like to get @mbroecheler to weigh in on this given his historic perspective on the matter as its related to Titan.

**Comment by mbroecheler** [comment]
Whether you do ```v.singleProperty(name,value)``` or ```v.property(single,name,value)``` is syntactically irrelevant. Semantically, this could get confusing for statically typed systems like Titan. If the user does ```v.property(single,..)``` on a multi-property then we could make it a runtime single property (i.e. read and remove all existing values) but the other way around won't work (and cause an exception?).

Moreover, for statically typed systems, the user would simply use ```v.property(name,value)``` which then uses the defined multiplicity of the property key. But against a dynamically typed system that would need to be made explicit. Hence, we loose code compatibility across vendors. On the other hand, if we make it mandatory to specify the multiplicity for each call, then statically typed systems are at a disadvantage because types can no longer be updated by changing the schema.

**Comment by okram** [comment]
@mbroecheler  .... so....? ... do we keep `v.singleProperty()` (in other words, leave the API as it is right now).

**Comment by mbroecheler** [comment]
I don't really now. I keep going back and forth on this.

```property(key,value)``` could assume the default multiplicity. For a statically typed graph like Titan that would be the multiplicity defined for the key. For a dynamically typed graph like TinkerGraph we could make the default configurable at the graph level. So, a user could make the default ```single``` in which case TinkerGraph behaves as in TP2. That might make it a lot easier for people to transition.

Then, there is the possibility to explicitly reference the multiplicity ```property(multiplicity,key,value)```. The only problem here is that the referenced multiplicity might be more permissive than the multiplicity configured for the key. I suppose the only way to react to this is to throw an exception.

**Comment by okram** [comment]
Your last paragraph is what I'm thinking.

```java
v.property(single,'name','marko') // the default impl will delete all the existing names and add marko
v.property(set,'name','marko')) // the default impl will look for name=marko and if it exists, return.
v.property(list,'name','marko')) // the default impl will simply add the property 
```

NOTES:

. `v.property(single,'name','marko')` is currently what we have called `v.singleProperty('name','marko')`
. `v.property(list,'name','marko')` is currently what we have called `v.property('name','marko')`
. `v.property(set,'name','marko')` would be a new behavior.

Finally, I would not introduce any notion of "default" behavior switching. The default is `v.property(list,...)`. If the vendor has a different cardinality in its schema, then they will throw an exception.

**Comment by mbroecheler** [comment]
Why not switch the default behavior? If a user has defined a key K in Titan as single-valued, then why not interpret ```v.property(K,value)``` as ```v.property(single,K,value)``` and thereby have the user benefit from a static type system rather than throwing an exception?

**Comment by okram** [comment]
Are you saying that for each key, they can register a `Cardinality`? A little too "schema" for TinkerPop?

```java
Map<String,Cardinality> 
```

**Comment by mbroecheler** [comment]
No, I am only talking about Titan which has a schema. Essentially, I think it would be nice if users only needed to type ```v.property(key,value)``` when dealing with Titan since the cardinality will be inferred from the schema.

**Comment by okram** [comment]
Dah. Apache doesn't close these tickets... of course. Anywho, this is closed. `VertexProperty.Cardinality` now exists. There no longer exists `Vertex.singleProperty()`, but instead `Vertex.property(cardinality, key,value,keyValues...)`.
