### ISSUE TITLE
New thoughts on looping constructs in Gremin3.

### ISSUE THREAD

**Issue by okram** [tinkerpop/tinkerpop3#411]
Now that we have "mastered" internal traversals and we know how to compile them into a linear form for OLAP execution, we can re-think the looping construct if we want.

Below are two examples demonstrating a proposal for "while/do" and "do/while", respectively. Moreover, for a more "graph feel", we can call `until` `loop`.

```java
// in Gremlin-Java
g.V().until(t -> t.get().value('name').equals('marko'), g.of().out())
g.V().until(g.of().out(), t -> t.get().value('name').equals('marko'))
```

```groovy
// in Gremlin-Groovy with Sugar
g.V.until({it.name == 'marko'}, g.of().out)
g.V.until(g.of().out){it.name == 'marko'}
// with the emit predicate
g.V.until({it.name == 'marko'}, g.of().out){true}
g.V.until(g.of().out){it.name == 'marko'}{true}
```

/////////////

A few extra thoughts:

* Rules of sideEffect scoping. If internal traversals are always "linearized" for OLAP, then we may want to make the sideEffect scope be the global scope. That is, no nested sideEffect structures.
* What I like about this model is that there is no need for `as()` and the section of what is being looped is being made apparent by `(`. This is what I like about `local()` as well. `( )` is the delimiter of the construct.
* We we still need to keep `jump()` as the `goto` construct necessary for arbitrary jumping, but it would be used primarily by the strategies (not by users). In fact, we could probably remove `GraphTraversal.jump()` and there would simply be a `JumpStep` available for usage by strategies. In fact, we could renamed `JumpStep` to `GoToStep`. Though, to keep with the graph-theme, "jump" may be more appropriate -- analogous to "loop" vs. "until".

@dkuppitz @mbroecheler @BrynCooke @joshsh

**Comment by okram** [comment]
More thoughts on this. Here are the concepts we need to maintain inside of a "looping" structure.

  * Path expression: the path to loop over. (**repeat**)
  * Break predicate: whether to continue looping. (**until**)
  * Emit predicate: whether to emit the object currently about to loop again. (**emit**)

```java
g.V().until(3).repeat(g.of().out('knows')) // while/do
g.V().repeat(g.of().out('knows')).until(3) // do/while
```

`until()` is a *pseudo-step modulator* for `RepeatStep` and it has the following signatures:

```java
until(Predicate<Traverser>) // most generic
until(integer) // less than or equal to loops
until(key,predicate,value) // like has('name','marko')
until(Object) // the traverser.get().equals(object)
```

Now `emit()` is identical to `until()` in that its placement before or after `repeat()` determines whether it is called prior or post repetition. Likewise, it has the same method signatures. An example of `emit()` is below:

```java
dog.until(label,'person').repeat(g.of().out('knows')).emit('label','cat').values('name')
```

 * if the current object is a person, do `out('knows')`.
 * after the `out(knows')` sequence, if the element is a cat, emit it.
 * send the traverser back to the `until()`.
 * return the names of all the cats and people.

### NOTES

* If `until(3)` looks odd, we could have `until(loops,lte,3)`, where `T.loops` exists.
* If no `until()` is provided, then it is assumed `until(t -> true)`.
* If no `emit()` is provided, then it is assumed `emit(t -> false)`.

I am not happy with `until()` and `emit()` in that they are basically just "filters", where the general pattern is: `filter.repeat.filter`:

```java
g.V().has(label,'person').repeat(...).has(label,'cat')
```

The problem is that you don't know if the `has()` is an `emit()` or an `until()` and if its part of the `repeat()` or "just some" `has()`. Fine, `emit()` and `until()` are good. What about chaining them?

```java
g.V().until('name','marko').until('age',32).repeat(...)...
```

I don't like this cause then we are just going to have a repeat of a lot of different methods in `GraphTraversal`.... The most generic is actually this, though its verbose:

```java
g.V().until(g.of().has(label,'person')).repeat(g.of().out('knows')).emit(g.of().has(label,'cat'))
```

Eek...ugly. Perhaps we do:

```java
until(Predicate<Traverser>)
until(integer)
until(key,predicate,value)
until(Object)
until(Traversal) // can be a whole complicated sequence there....
```

Thoughts on anything anyone?

**Comment by dkuppitz** [comment]
One thing I don't understand:

> ```groovy
> dog.until(label,'person').repeat(g.of().out('knows')).emit('label','cat').values('name')
> ```
> * ...
> * return the names of all the cats and people.

It's only the names of all cats, not people, right?

And regarding the chaining of multiple break and/or emit pedicates, I concur that ```until(Traversal)``` is the best solution (```.until(...).until(...)``` shouldn't be allowed).

**Comment by okram** [comment]
Adding @mpollmeier as he recently wrote a blog post on Gremlin-Scala and looping with `jump()`. I want to make sure he is part of this discussion.

**Comment by okram** [comment]
This is what it looks like in Gremlin-Java.

```java
g.V().repeat(g.<Vertex>of().out()).until(2).forEachRemaining(System.out::println);
// vs
g.V().as('x').out().jump('x',2).forEachRemaining(System.out::println);
```

**Comment by davidcrouch** [comment]
Thumbs up :-)

**Comment by okram** [comment]
So `RepeatStep` is all plugged in with `BranchStep` being the step used for compiling it to its linear form for OLAP. All the test cases in `JumpTest` were adopted to `RepeatTest` and a few more added now that we have an extra flexibility around the `emit()` being in a different area than `until()`. At this point `JumpStep` is no longer needed as `RepeatStep` does 90% of `JumpStep` and `BranchStep` takes care of the other 10% (e.g. `jump('a')` -- jump to an arbitrary step).

I added documentation so you can see it in action:
  http://www.tinkerpop.com/docs/3.0.0-SNAPSHOT/#repeat-step

I have fixed up `ChooseStep` and `UnionStep` to use `BranchStep` for their compilation to OLAP. As such, there is no need for `JumpStep` anymore. Tomorrow I will gut it and at that point, we will be done with `jump()` forever.

Finally, I added `GraphTraversal.branch()` that allows you to do this (see #234):

```groovy
g.V().branch().by{it.name == 'marko' ? ['a'] : ['b']}.as('a').name.as('b')
==>marko
==>v[2]
==>v[3]
==>v[4]
==>v[5]
==>v[6]

 ... `branch()` serves as our "lambda step" for branching operations. There is still a bit more work I need to do on `BranchStep`. Once its cleaned up and pretty and I have gutted `JumpStep`, I will close this ticket.

**Comment by okram** [comment]
Dah.

```groovy
gremlin> g.V().as('x').both().groupCount('m').by{it.value('name')[1]}.jump('x',10).cap('m')
==>[a:19598, e:5740, i:5740, o:27716]
gremlin> g.V().repeat(g.of().both().groupCount('m').by{it.value('name')[1]}).until(10).cap('m')
Side effects do not have a value for provided key: m
Display stack trace? [yN]
```

This gets to the problem of "variable frames" in Gremlin. With nested traversals, do the sideEffects all exist on the same frame? Bummer.........

**Comment by mpollmeier** [comment]
Hey, just commenting because you mentioned me - I don't think I can add much to the discussion - I don't have the full overview of the subtleties of repeat vs branch vs jump. 
FWIW I'm always happy to remove a step if the same can be achieved with another one.
