### ISSUE TITLE
Introduce (T)oken self?

### ISSUE THREAD

**Issue by okram** [tinkerpop/tinkerpop3#428]
Right now we have it such that `T implements Function<Element,Object>`. This is great because you can now do things like:

```java
T.id(element)
T.label(element)
...
```

When doing `by()`-projections, it is important to support "it" in some way and I think a token would be good for this.

```groovy
g.V.as('a').out.as('b').select('a','b').by('name').by{it} // currently how its done
```

If we include `T.self(element) -> element`, then it would be:

```groovy
g.V.as('a').out.as('b').select('a','b').by('name').by(self) // currently how its done
```

Is that cool? Is "self" a good token term to use? Will it conflict with other programming languages?

**Comment by okram** [comment]
Perhaps its just `by()` which calls `by(x -> x)`.

**Comment by dkuppitz** [comment]
Hm, although I prefer less typing, ```.by()``` looks odd. I like ```.by(self)```. Do you think the impact of changing ```T implements Function<Element,Object>``` to ```T implements Function<Object,Object>``` would be too bad?

**Comment by okram** [comment]
I noticed your comment. `T.self` ONLY works for `Element` (can't change `T` to implement `Function<Element,Object>`). ..... .... ?... any ideas.

**Comment by dkuppitz** [comment]
```T2 implements Function<Object,Object>``` :)

No idea. Maybe we / I just need to get used to empty ```.by()```'s.
