### ISSUE TITLE
Neo4j g.V(ids).has(...) optimization

### ISSUE THREAD

**Issue by pietermartin** [tinkerpop/tinkerpop3#451]
I noticed that a query of the form `this.g.V(1L,2L).has(T.label,"Person")` will first retrieve all Persons and then filter out on the ids.

Perhaps if there are given `ids` then we can assume that the given ids should be the first narrowing of the elements and then filter on the `has` clause?

**Comment by okram** [comment]
Hi @pietermartin. Do you think you could provide a pull request? Not that this will also apply to `TinkerGraphStep`. So.....

**Comment by pietermartin** [comment]
Yes, if not sooner then by the weekend.

**Comment by okram** [comment]
I believe everything was done and this can be closed. If not, please reopen with what is needed still.
