### ISSUE TITLE
Packaging around Groovy "plugins"

### ISSUE THREAD

**Issue by okram** [tinkerpop/tinkerpop3#452]
If plugins are specific to Groovy, then looking at `ext/plugins.txt`.

```
com.tinkerpop.gremlin.console.plugin.DriverGremlinPlugin
com.tinkerpop.gremlin.console.plugin.UtilitiesGremlinPlugin
com.tinkerpop.gremlin.tinkergraph.groovy.plugin.TinkerGraphGremlinPlugin
```

...should we either add `groovy` to Driver and Utilities or remove it from TinkerGraphGremlinPlugin?

**Comment by spmallette** [comment]
done - moved console plugins to `com.tinkerpop.gremlin.console.plugin`
