### ISSUE TITLE
Using enums to solve the g.of() anonymous traversal problem. [proposal]

### ISSUE THREAD

**Issue by okram** [tinkerpop/tinkerpop3#453]
### PROBLEM

Now that we can allow nested traversals given that cloning and resetting are native concepts to `Step`, we will start to see a lot more *anonymous traversal* creation via `g.of()` (e.g. `match()`, `choose()`, `local()`, ...and soon, `repeat()` https://github.com/tinkerpop/tinkerpop3/issues/411#issuecomment-68500911).

```java
g.of().out().in()
```

In Gremlin2 (and Gremlin1), we supported `_()` for anonymous traversals. There are two problems with this:

  . `_` is **not** a legal variable or method name in Java8+.
 . `_` is **not** tied to a `Graph` so you don't know which graph engine you are using and thus, no strategies, no DSLs, etc.

### POTENTIAL SOLUTION

I propose that each vendor provides a `G` enum in their `GraphTraversal` implementation.

```java
public TinkerGraphTraversal<S,E> implements GraphTraversal<S,E> {
   public static enum G implements GraphTraversal {
     _g {
        public GraphTraversal start() {
           return new TinkerGraphTraversal().start();
        }
     }
   }
}
```

Now, `_` by itself is no longer allowed in Java8, but `_g` is. So, with `static import`, you can do this:

```java
g.V().out().local(_g.outE().order().by('weight').limit(10).inV()).values("name")
   // vs
g.V().out().local(g.of().outE().order().by('weight').limit(10).inV()).values("name")
```

*"So that is all fine and dandy, but what about DSLs (...like `Neo4jGraphTraversal` that supports `cypher()`)."*

```java
public Neo4jGraphTraversal<S,E> implements Neo4jTraversal<S,E> {
   public static enum G implements Neo4jTraversal {
     _g {
        public Neo4jTraversal start() {
           return new Neo4jGraphTraversal().start();
        }
     }
   }
}
```

Thus, when `g instanceof Neo4jGraph`:

```
g.V().out().local(_g.cypher('MATCH (a)->(b)').select('a'))
```

In this way, it is assumed that the user's code base is tied to a particular vendor implementation and thus, they won't `static import` `G` from OrientDB and Neo4j at the same time. ... the only counter argument is the use of `TinkerGraph` and `Neo4j` being used at the same time :( (discussed later).

The two problems mentioned in the first section are now solved:

  . `_g` is a legal, reasonable character sequence to start an anonymous traversal.
  . `_g` is provided by the vendor and thus, tied to the DSL/strategies of that vendor.

### PROBLEM WITH TWO GRAPHS IN THE SAME CODEBASE

Lots of people will use TinkerGraph with their preferred graph engine (e.g. Neo4j, Titan, OrientDB, etc.). This raises the issue of `_g` being statically imported from two places. With:

```java
TinkerGraphTraversal { public enum G ... }
Neo4jGraphTraversal { public enum G ... }
```

You can `import static` one, and not the other:

```java
tinker.V().local(TinkerGraphTraversal.G._g.outE().inV()).values("name")
neo4j.V().local(_g.outE().inV()).values("name")
```

Sorta crappy...or we stick with `g.of()`. (which, of course, is the easiest for me :)).

### CONCLUSION

Thoughts?

@dkuppitz @mbroecheler @spmallette @mpollmeier

**Comment by dkuppitz** [comment]
I don't think ```g.of()``` is too bad, but if you want to get rid of it, then don't use ```_g``` as it's not a reference to the graph object, but to any specific element (a vertex, an edge or just a property). A better choice would be something like ```it```, ```el```, ```curr``` or ```self```.

**Comment by okram** [comment]
One of the cool things about the enum model, is we could also do this:

```java
public static enum G implements GraphTraversal {
     _g {
        public GraphTraversal start() {
           return new TinkerGraphTraversal().start();
        }
     },
     as(String stepLabel) {
          // not quite keen on the Java code right now, but hopefully you get the concept...
        }
     };
   }
```

```java
g.V().match(
  as('a').out('knows').as('b')
  as('b').out('created').as('c')
).select('c').by('name')
```

versus how it is currently:

```java
g.V().match(
  g.of().as('a').out('knows').as('b')
  g.of().as('b').out('created').as('c')
).select('c').by('name')
```

**Comment by okram** [comment]
I don't like `enum`-model cause its, as @dkuppitz is telling me in IM, more code, more things for vendors to do, etc. However, in favor of `enum`-model, just this kicker.

We have always been talking of `g.of()` which generates some `GraphTraversal`. How about DSLs that are user created (not like `Neo4jGraphTraversal` which is the default `GraphTraversal` for `Neo4jGraph`). The way you currently do this is:

```java
g.of(SocialTraversal.class).people().know().name()
```

If we keep with the `g.of()` model, that is alot of typing for DSL users that have anonymous DSL traversals. E.g.:

```java
g.of(SocialTraversal.class).people().local(g.of(SocialTraversal.class).know().limit(2)).name()
```

With the `enum`-model, both vendors of graph engines as well as DSLs (e.g. `SocialTraversal`) will provide their enum. Thus, for `SocialTraversal` they  could have `_g`, but to not confuse, `_social`:

```java
g.of(SocialTraversal.class).people().local(_social.know().limit(2)).name()
```

.....just more notes on pros and cons.

**Comment by dkuppitz** [comment]
That looks good, then it's just a best practice for DSL implementations.

```java
public static enum G implements GraphTraversal {
     _social {
        public SocialTraversal start() {
           return new SocialTraversal().start();
        }
     }
}
```

Users can do that for their own DSLs to simplify nested traversals, but they don't have to.

**Comment by okram** [comment]
`__` is legal in Java8. Thus, instead of `_g` we can do:

```java
g.V().repeat(__.out()).until(2).values('name')
  -vs-
g.V().repeat(_g.out()).until(2).values('name')
  -vs-
g.V().repeat(g.of().out()).until(2).values('name')
```

??........... I really don't like `g.of()` now that `repeat()` exists.

**Comment by dkuppitz** [comment]
```__``` is better than ```_g```, but I would still prefer one of my previous suggestions: ~~```it```~~, ```el```, ```curr``` or ```self```.

**Comment by mbroecheler** [comment]
I like using __ for anonymous traversals. _g can easily be confused with g which is likely the variable used to hold the graph. I think it it important to clearly differentiate between bound traversals like ```g.V.out()``` and unbound or anonymous traverals ```__.out()```

**Comment by mpollmeier** [comment]
I prefer `__`, however given that `_` has a special meaning in e.g. java 8 and scala I can understand if some people prefer `it`, `el`, `curr`, or `self` as @dkuppitz proposed.
You could either flip a coin or have both options and leave it up to the user to decide (not ideal either).

**Comment by okram** [comment]
So, enums have some shortcomings -- 1. you can't implement clone() and 2. you can't attach generics. Thus, you can't clone for OLAP and you can't do `<S,E>` typing and therefore, the entire traversal is un-typed and ugly useless requiring casting (with IDEs making highlighting the traversal with yellow WARNING). 

**If you want to use an enum then the vendor has to implement each method as enums can not extend each other and thus, we can't provide a base enum.**

**The vendor can always, super easy copy/paste from a provided filled out enum and then provide their own implementation of `start()`. but that sort seems ghetto.....**

```java
public enum AnonymousTraversal {    // TinkerGraph's anonymous traversal provider.

    __;

    public <S> GraphTraversal<S, S> start() {
        return new DefaultTinkerTraversal<>(); // the key method which is what I was hoping would be the only thing the vendor would have to have in their enum class
    }

    public <S, E, E2> GraphTraversal<S, E2> map(final Function<Traverser<E>, E2> function) {
        return this.<S>start().map((Function) function);
    }

    public <S, E, E2> GraphTraversal<S, E2> flatMap(final Function<Traverser<E>, Iterator<E2>> function) {
        return this.<S>start().flatMap((Function) function);
    }

    public <S> GraphTraversal<S, Object> id() {
        return this.<S>start().id();
    }

    public <S> GraphTraversal<S, Vertex> out(final String... edgeLabels) {
        return this.<S>start().out(edgeLabels);
    }

   /// and of course the list will go on and on and on...
}
```

And then, with an `import static`, you can now do:

```java
    public static void main(String[] args) {
      Graph g = TinkerFactory.createClassic();
      g.V().repeat(__.out()).until(2).values("name").forEachRemaining(System.out::println);
    }

// lop
// ripple
```

**Comment by okram** [comment]
Got it.

```java
public enum TinkerToken implements AnonymousGraphTraversal {
    __;

    public <S> GraphTraversal<S, S> start() {
        return new DefaultTinkerTraversal<>();
    }
}
```

`AnonymousGraphTraversal` is an interface in `gremlin-core/`. Thus, we (as TinkerPop), just need to update that interface accordingly when `GraphTraversal` updates.

**Comment by okram** [comment]
I connected it to `TinkerGraphGremlinPlugin` so it is `import static` when the plugin loads. (@spmallette -- will be interesting to see how it behaves when you also have Neo4j's `__` imported too..?)

```
~/software/tinkerpop/tinkerpop3$ bin/gremlin.sh

         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----
plugin activated: tinkerpop.server
plugin activated: tinkerpop.utilities
plugin activated: tinkerpop.tinkergraph
gremlin> __
==>__
gremlin> __.getClass()
==>class com.tinkerpop.gremlin.tinkergraph.process.graph.util.DefaultTinkerGraphTraversalTokens
gremlin>
gremlin> g = TinkerFactory.createClassic()
==>tinkergraph[vertices:6 edges:6]
gremlin> g.V().repeat(__.out()).until(2).values('name')
==>ripple
==>lop
```

@mbroecheler --- I thought that you could provide argument constructors to enums, but alas you can't -- there are no public constructors for enums. Thus, I can't do `as('a').out.as('b')`... suxoids. 

Next, for the test suite, there is no way to know which `__` to use unless I work with @spmallette to expose some sort of `getTraversalTokens()` method in `GremlinTestSuite`. I think it should be easy, I just don't know Stephen's code. Once that happens, then we will able to update all the test-cases to use `__`.

Finally, we may be able to get rid of `of()` all together. HOWEVER, if a developer has two graphs, then they can't have both `__` imported statically. I think that `of()` may be a nice happy middle so they don't have to do `g.V().repeat(DefaultTinkerGraphTraversalTokens.__.out()).until(2).values('name')`. HOWEVER, perhaps we rename `Graph.of()` to `Graph.__()` and thus, they can do `g.__` if they don't have the token imported statically.

For a fun review...this is all a vendor needs to provide.

```java
public enum DefaultTinkerGraphTraversalTokens implements AnonymousGraphTraversal {
    __;
    public <S> GraphTraversal<S, S> start() {
        return new DefaultTinkerGraphTraversal<>();
    }
}
```

Neo4j will have one more method... `cypher()` and it as well as `start()` will return a `Neo4jGraphTraversal<S,S>`.

**Comment by okram** [comment]
Or! `Graph.of()` goes away and `g.__` is simply a public field of the graph. BAM.

And now I don't need anything for TestSuites from @spmallette

**Comment by mbroecheler** [comment]
Here is a thought: Why do we need ```__``` tied to a graph at all? Why can we not have truly anonymous traversals that can be passed around between graphs as needed? Is the only reason that we need to apply the strategies which are graph specific? If so, then I would argue that anonymous traversals are never used by themselves but are always embedded in a "real" traversal which could then ground the anonymous traversal inside.

**Comment by okram** [comment]
There are a couple of reasons:

  1. Traversal strategies are `Traversal` dependent, not `Graph` dependent. If someone has a DSL, they will have strategies for it. That DSL will work over Titan, TinkerGraph, or Neo4j. Now, that DSL will rely on `GraphTraversal` methods under the hood and thus, leverages the traversal strategies of the underlying graph. E.g.: 
```java
public SocialTraversal<S,E> extends Traversal<S,E> {
  public SocialTraversal<Person,Product> likes(int minStars) {
    return new MapStep<Person,Product>(traverser -> new Product(traverser.get().getVertex().outE('likes').has('stars',Compare.gte,minStars).inV().next())
  }
  /// more methods
}
```
 
  2. Neo4j's `GraphTraversal` is like a DSL in that it has an added method -- `cypher()`. If `__` was not tied to a graph, then you couldn't do this: `g.V.out.repeat(__.cypher('MATCH ...').select('b').out).`

**Comment by mbroecheler** [comment]
How about a dual strategy then?

1) ```__``` creates a truly anonymous traversal that is not bound to a graph or traversal. It only supports the standard steps and must be bound to a graph before execution (i.e. either by being used inside a graph-bound traversal like ```g.V.out.repeat(__.out('likes'))...``` or by being attached to a graph - for instance when used inside VertexProgram). For most use cases, this is sufficient and makes it very easy to pass around anonymous traversals.

2) ```g.___``` creates a graph bound anonymous traversal which will support all graph specific extensions (e.g. cypher) and DSLs. A user would only use that if she needed such additional functionality.

The beauty of this approach is that the two ways are syntactically similar and it makes "sense": if you need something special from the graph, you need to reference it when constructing an anonymous traversal. If you don't, then you can create an unbound anonymous traversal that can be passed between graphs which is great for lots of applications where you would want to define incidences without being graph specific.

**Comment by okram** [comment]
What we can do is this (and I need to do it anyways for something else).

We can have `GraphTraversal.__` be an enum that returns a `DefaultGraphTraversal` which is the barebones implementation of `GraphTraversal` -- its basically `GraphTraversal.of()` but not a method, but an enum (https://github.com/tinkerpop/tinkerpop3/blob/293270b73ff36e91b4279905787aa0f574a1d258/gremlin-core/src/main/java/com/tinkerpop/gremlin/process/graph/GraphTraversal.java#L118-L120). This is, of course, vendor neutral (or more accurately, TinkerPop as the vendor). Next, `DefaultGraphTraversal` has its own strategies (in the `TraversalStrategyCache`), so I will need to make it so strategies can be set dynamically, where `repeat(__.out())` will apply the strategies it has to the anonymous traversal.. This is needed for another ticket, but haven't gotten around to it. #461

In terms of 2, there is nothing wrong with having `Neo4jGraphTraversal.__` that is imported statically which returns a `Neo4jGraphTraversal` so you can get the fluency for `cypher()`. This applies to any DSL for that matter.

The only problem that remains is actually getting that enum when you can't import statically. `g.__()` may be the best way for 2 situations: 1). our test suite and 2.) when you have two graphs in your application (e.g. you are working with both Neo4j and TinkerGraph).

**Comment by mbroecheler** [comment]
Having the enum as GraphTraversal seems fine. I am not sure injecting strategies into an unbound anonymous traversal is a good idea. Unbound anonymous traversals would allow cool things like defining them ahead of time:
```
goodFriendsOfFriends = __.outE('friend').has('weight',5).inV().outE('friend').has('weight',5).inV()
```
which can then be used in traversals ```g.V(5).repeat(goodFriendsOfFriends).until(...)``` or a VertexProgram.
If we inject the strategies into the traversal, then the traversal is modified which can cause strange behavior when dealing with multiple graphs or in a multi-threaded setting. Wouldn't it be better to check if the traversal is unbound, and if so copy the traversal to the current graph as it is done in the messaging component of GraphComputer?

Yes, you could have ```Neo4jGraphTraversal.__``` but it would be nice to have ```GraphTraversal.__``` be statically imported by default in the gremlin shell and server so that users don't have to make that import manually. In that case, the two would conflict. 
That would also get around the problem of not being able to statically import. Only the default traversal is statically imported. If you need a graph specific one you refer to it through ```g```

**Comment by okram** [comment]
Cool -- I like referencing traversals for later. We have done a solid job making sure `Object.clone()` is implemented correctly in TinkerPop3. This means we can do, as you say:

```java
goodFriendsOfFriends = __.outE('friend').has('weight',5).inV().outE('friend').has('weight',5).inV()
```

This will be a `DefaultGraphTraversal`. This is "vendor neutral." Now when you do this:

```java
g.V().repeat(goodFriendsOfMine).until(2)
```

...not only are the strategies of the vendor specific traversals injected (as we get those once we do `g.V()`), but the `goodFriendsOfMine` is cloned. Thus, the original `goodFriendsOfMine` is there in the vendor agnostic form and available to some other graph vendor/thread/etc.

This is easy to do. We simply make `clone()` calls in `RepeatStep`, `UnionStep`, `ChooseStep`, `MatchStep`, ??.. think thats it. And, I need to do the "dynamic addition of strategies" in #461 and then you can apply the strategies from `g` to the cloned anonymous traversal to make it "vendor specific" prior to execution.

/////////////////////////////

I see your point that if someone really really wants to use Cypher in an anonymous traversal, then they will do `g.of()`. For instance:

```java
neo4j.V().cypher().select().repeat(_.out()).until(2)) // works fine
neo4j.V().cypher().select().repeat(_.out().cypher()).until(2) // doesn't recognize cypher() method
```

Thus, if you want to use `cypher()` anonymously, you would do:

```java
g.V().cypher().select().repeat(g.of().out().cypher()).until(2)
```

...we can also rename `g.of()` to `g.__()` so it has the same look and feel as the enum.

```java
g.V().cypher().select().repeat(g.__().out().cypher()).until(2)
```

Finally, for arbitrary DSLs, they will have their own enum. Like we talked about previous on this thread -- `_social`. Thus, there is no naming conflict.

```java
g.of(SocialTraversal.class).people().named("bob").who().workFor("acme").repeat(_social.knows()).until(2)
```

...ah..still need `g.of()` for DSLs............................

**Comment by okram** [comment]
Okay. Here you go:

```
~/software/tinkerpop/tinkerpop3$ bin/gremlin.sh

         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----
plugin activated: tinkerpop.server
plugin activated: tinkerpop.utilities
plugin activated: tinkerpop.tinkergraph
gremlin> __
==>__
gremlin> __.getClass()
==>class com.tinkerpop.gremlin.process.graph.AnonymousGraphTraversal$Tokens
gremlin> t = __.out(); null
==>null
gremlin> t.getClass()
==>class com.tinkerpop.gremlin.process.graph.util.DefaultGraphTraversal
gremlin> t.asAdmin().getTraversalStrategies()   /////// ALL VENDOR AGNOSTIC STUFF HERE
==>strategies[RepeatLinearStrategy, DedupOptimizerStrategy, IdentityRemovalStrategy, SideEffectCapStrategy, MatchWhereStrategy, ChooseLinearStrategy, UnionLinearStrategy, ComparatorHolderRemovalStrategy, ReducingStrategy, LabeledEndStepStrategy, EngineDependentStrategy]
gremlin>
gremlin>
gremlin> g = TinkerFactory.createClassic()
==>tinkergraph[vertices:6 edges:6]
gremlin> g.V().repeat(t).until(2)
==>v[5]
==>v[3]
gremlin> t.asAdmin().getTraversalStrategies() /////// NOTICE TinkerGraphStepStrategy IS THERE
==>strategies[RepeatLinearStrategy, DedupOptimizerStrategy, IdentityRemovalStrategy, SideEffectCapStrategy, MatchWhereStrategy, ChooseLinearStrategy, UnionLinearStrategy, ComparatorHolderRemovalStrategy, ReducingStrategy, LabeledEndStepStrategy, EngineDependentStrategy, TinkerGraphStepStrategy]
gremlin>
```
