### ISSUE TITLE
reflections.org in testing -- should we keep it?

### ISSUE THREAD

**Issue by okram** [tinkerpop/tinkerpop3#456]
This is to the point of getting rid of <dependencies/> that we are not strongly relying on. The less dependencies the better. In gremlin-test/:

```xml
        <dependency>
            <groupId>org.reflections</groupId>
            <artifactId>reflections</artifactId>
            <version>0.9.9</version>
        </dependency>
```

Is this needed? It uses Guava (but the scope is only test so not so bad)... but also, can we gut it so its one less dependency?

Refs #444

**Comment by spmallette** [comment]
I'm don't think we can easily get rid of this - I use it to dynamically search the classpath for implementations of certain interfaces that are needed when you want to clear the groovy `MetaRegistry` which in turn allows sugar tests to pass.  We could only drop it if we don't want to have a default implementation of this method:

https://github.com/tinkerpop/tinkerpop3/blob/a7957754b557d8ae0055031c9bb561154cddf341/gremlin-test/src/main/java/com/tinkerpop/gremlin/GraphProvider.java#L203

In which case, vendors would have to register their classes manually.  I suppose that's not a big sacrifice, just one more thing for them to do.  wdyt?

**Comment by spmallette** [comment]
Removed `reflections` from `gremlin-test`. This means that vendors will have to implement the `GraphProvider.getImplementations()` method themselves and manually register classes as they are no longer found automatically via reflection.

**Comment by okram** [comment]
Can you provide the relfection behavior yourself? That is, provide an implementation of what reflections.org was doing?

**Comment by spmallette** [comment]
My research tells me that it isn't trivial.
