### ISSUE TITLE
[Proposal] OrderMap for Gremlin3

### ISSUE THREAD

**Issue by okram** [tinkerpop/tinkerpop3#458]
In Gremlin2 we have `OrderMapStep` which orders the maps flowing through the step. However, what about if you had lists flowing? `OrderListStep`, `OrderStringStep`, `OrderArrayStep`, etc.

Here is a generalization:

```groovy
g.V().out().groupCount().by('age').cap().orderObject().by(incr)
```

What sucks is that we have `order()` for stream ordering and `orderObject()` for per object ordering. This is very similar to the problem with `local()`. Sometimes you want the process local to the object. As such, do we simply promote this:

```groovy
g.V().out().groupCount().by('age').cap().map{it.get().sort()}
```

But that looks lame...and uses Groovy `sort()` where we want something general to Java and Groovy.

```groovy
g.V().out().groupCount().by('age').cap().local(Order.incr)
```

Where `LocalStep` takes not just a `Traversal` but also a `Function<Traverser,Traverser>` where `Order.incr` is a Function.................

Grasping for straws here....ideas?

@mbroecheler @dkuppitz @spmallette @bryncooke

**Comment by mbroecheler** [comment]
Applying an operation to each element in the pipeline is what ```map``` is for. Hence, I would argue that we should provide some utility or function that makes it easy to express a local order inside a map without having to resort to a groovy method. Maybe we could introduce a ```mapElement``` step that applies the provided lambda to the element of the Traverser (hence saving the ```it.get()```) and a pre-defined sorting lambda?

**Comment by okram** [comment]
There is another reason to come up with a general solution. `dedup()`. Dedup the elements in a list...

Perhaps we use step modulators again?

```groovy
gremlin> g.V.groupCount.by('age').cap.order.item(incr)
==> // order map
gremlin> __.inject([1,1,1,2],[1,2],[3,3,2]).dedup.by('name').item()
==>[1,2]
==>[1,2]
==>[3,3,2]
gremlin> __.inject([1,1,1,2],[1,2],[3,3,2]).shuffle.item()
==>[1,2,1,1]
==>[2,1]
==>[3,2,3]
```

...weird, those are all barrier steps! huh, perhaps the concept is, "all barrier steps need a local form that simply operates on the current object." ??? What do you guys think of `item()` ?? I don't like the word...anything better?

**Comment by dkuppitz** [comment]
Maybe ```.each()```? It wouldn't conflict with Groovy's ```each```, if you can make it so that it never requires an argument.

```groovy
gremlin> g.V.groupCount.by('age').cap.order(incr).each()
==> // ordered map
gremlin> __.inject([1,1,1,2],[1,2],[3,3,2]).dedup.by('name').each()
==>[1,2]
==>[1,2]
==>[3,3,2]
gremlin> __.inject([1,1,1,2],[1,2],[3,3,2]).shuffle.each()
==>[1,2,1,1]
==>[2,1]
==>[3,2,3]
```

**Comment by mbroecheler** [comment]
Mmh, I am not sure I would go there. Gremlin is a graph traversal language - it feels strange to provide support for operating on the internal data structures of the items flowing through the pipeline. Aren't we overdoing it if we provide support for this? And are users actually going to understand this?

Imho, there should be ```map{}``` for doing such things. Maybe ```mapItem{}``` to avoid the ```get()```. Anything beyond that becomes an academic exercise.

**Comment by okram** [comment]
I see the spread operator being used in Groovy to apply a function to each individual object of a collection, not to the collection as a whole. Can we leverage that concept here?

```java
g.V().out().valueMap().order(spread).by(incr) // map order
g.V().out().local(__.values('startTime').fold()).order(spread).by(incr) // list order
g.V().local(__.out().values('name').fold()).dedup(spread) // list dedup
... // etc.
```

...where `spread` is a token enum. Don't really like the word "spread," but what is good about this is that if you call `order(spread)` that will trigger an OrderSpreadStep (not an OrderStep) and thus, a non-barrier, local processing step.

If there is no other concept besides `spread` in that "token space," then it could just be `orderLocal`, `dedupLocal()`, `shuffleLocal()`, etc..... though I hate new step names.........................

Thoughts?

**Comment by okram** [comment]
Or `order(star)` .. or `order(local)`...., where `order()` is a shorthand for `order(global)`. ?........

**Comment by okram** [comment]
Check this out:

```java
g.V().map(v -> {
            final Map<Integer, Double> map = new HashMap<>();
            map.put(random.nextInt(10),random.nextDouble());
            map.put(random.nextInt(10),random.nextDouble());
            map.put(random.nextInt(10),random.nextDouble());
            return map;
        }).order(Scope.local).by(Order.keyIncr);
////////////
{6=0.1335616811711453, 8=0.1280666461022637}
{2=0.1202295898717528, 4=0.594528022224703, 5=0.9927364258992233}
{0=0.5412563108504247, 4=0.4195941110686683, 9=0.10316289228380804}
{0=0.462009617430139, 8=0.944354726461425}
{0=0.44653209028625274, 1=0.26897786157267267, 3=0.041369632149070634}
{3=0.43507178885864384, 4=0.1996935083075556, 7=0.33778440752532113}


g.V().map(v -> {
            final Map<Integer, Double> map = new HashMap<>();
            map.put(random.nextInt(10),random.nextDouble());
            map.put(random.nextInt(10),random.nextDouble());
            map.put(random.nextInt(10),random.nextDouble());
            return map;
        }).order(Scope.local).by(Order.valueDecr)
//////////////////
{6=0.9029129359384017, 2=0.41141187329225526, 4=0.3770353799898942}
{3=0.8861373488082026, 8=0.6728063235712354, 5=0.5502975955781219}
{0=0.528173565627075, 6=0.27385393173108996, 7=0.07357241205591991}
{4=0.8016225061192503, 8=0.525083945389597, 5=0.37842972548277065}
{2=0.8527569420147856, 4=0.5506888143094787, 3=0.49183042337133986}
{5=0.889121454899261, 1=0.5410335485329801, 4=0.45661255784965205}
```
