### ISSUE TITLE
Minor typo on Tinkerpop 3 intro page

### ISSUE THREAD

**Issue by graben1437** [tinkerpop/tinkerpop3#459]
On this page:
http://www.tinkerpop.com/docs/3.0.0.M6/#_tinkerpop3

The following text is found in The Traverser  section of text:

"traversal.next()'d"

The syntax - particularly the 'd  - 

isn't clear and I could not find an explanation and was wondering if the text should simply read:

"traversal.next()"

**Comment by okram** [comment]
That is not "syntax" as I want to make the code fragment a vertex by adding "`d". Its a language play.

e.g. play -> play'd
e.g. next() -> next()'d.
