### ISSUE TITLE
Go through all lambda steps and remove Traverser<S> and replace with <S>

### ISSUE THREAD

**Issue by okram** [tinkerpop/tinkerpop3#460]
The only steps that will support `Lambda<Traverser<S>>` will be `map()`, `flatMap()`, `filter()`, `sideEffect()`, `branch()`, and `repeat()`. All of those are generic lambda steps (besides `repeat()`). `repeat()` requires `Traverser<S>` so that loops can be checked.

Note that this has already been updated for most steps with `by()`-modulation. `groupCount().by('name')`. The only danglers that I can think of are `choose()`, `union()`, `fold()`, .. ??... 

This should make @mpollmeier happy as this was one of his suggestions back in M1 days.

**Comment by mpollmeier** [comment]
Very happy indeed ;)
