### ISSUE TITLE
[proposal] Provide cap(String...)

### ISSUE THREAD

**Issue by okram** [tinkerpop/tinkerpop3#462]
This way, people can do this:

```java
g.V.group('a').by('age').out('nationality').groupCount('b').by('name').cap('a','b')
```

They will get a `Map<String,Object>` of their sideEffects.

@dkuppitz @rjbriody

**Comment by dkuppitz** [comment]
I never needed this feature, but looks like a great idea.

**Comment by spmallette** [comment]
I kinda like the idea too - I think I've wanted to be able to do that before.

**Comment by rjbriody** [comment]
+1
