### ISSUE TITLE
Have times() be an alias to until()

### ISSUE THREAD

**Issue by okram** [tinkerpop/tinkerpop3#464]
This is a @dkuppitz idea.

```java
public GraphTraversal<S,E> times(final int loops) {
  return this.until(t -> t.loops() >= loops);
}
```

Then looping reads like this:

```java
g.V().repeat(__.out()).times(2)
```

It reads nice, but perhaps too much?

@mbroecheler @spmallette @mpollmeier

**Comment by mbroecheler** [comment]
+1

On Wed, Jan 7, 2015 at 4:46 PM, Marko A. Rodriguez <notifications@github.com
> wrote:

> This is a @dkuppitz <https://github.com/dkuppitz> idea.
>
> public GraphTraversal<S,E> times(final int loops) {
>   return this.until(t -> t.loops() >= loops);
> }
>
> Then looping reads like this:
>
> g.V().repeat(__.out()).times(2)
>
> It reads nice, but perhaps too much?
>
> @mbroecheler <https://github.com/mbroecheler> @spmallette
> <https://github.com/spmallette> @mpollmeier
> <https://github.com/mpollmeier>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tinkerpop/tinkerpop3/issues/464>.
>



-- 
Matthias Broecheler
http://www.matthiasb.com

**Comment by mpollmeier** [comment]
+1

With that, `until` can always take a traverser and doesn't need the 
overloaded `until(int loopCount)` (from memory)

**Comment by okram** [comment]
@mpollmeier -- as you recommended, there is no more `until(int)`, only `until(predicate<traverser>)`. On the `emit` side, we have `emit()` which is an alias to `emit(t -> true)`. Any other overloads, aliases, etc., please make a new ticket.
