### ISSUE TITLE
Move clock() to a Java8 method -- no need to just be in Groovy.

### ISSUE THREAD

**Issue by okram** [tinkerpop/tinkerpop3#467]
@dkuppitz

**Comment by dkuppitz** [comment]
Why would you use it in Java? I'm pretty sure that I'm never going to use utility plugin outside the REPL. But, on the other hand, I don't see any disadvantage either. So, if you like to have it available in Java -- have fun.

**Comment by okram** [comment]
@dkuppitz  -- this has your name all over it.

**Comment by dkuppitz** [comment]
Not sure where to put it. A new class ```TimeUtil``` just to have a single static method in there? I tend to put it into the ```Gremlin``` class.

**Comment by okram** [comment]
There is a `tools/` package that @mbroecheler created for `MultiMap`. You can put it there. `TimeUtil` works.
