### ISSUE TITLE
Thoughts on repeat step type signature

### ISSUE THREAD

**Issue by mpollmeier** [tinkerpop/tinkerpop3#470]
While porting the new repeat step (see https://github.com/tinkerpop/tinkerpop3/issues/453) I wondered (possibly due my lack of understanding):

1) `repeat` takes a `Traversal<?, E>` - shouldn't it instead take something like `Function<E, Traversal<E,E>>` as it always starts at an E?

If that's the case we wouldn't actually need the `__`. You would call it with something like this (excuse my lack of java8 syntax knowledge):
`g.V(1).repeat(_.out())` - which is equivalent to `g.V(1).repeat(Vertex v -> v.out())` 

2) Going one step further, why does repeat need to start and end with the same type? The signature could be like this instead:
`public default <E2> GraphTraversal<S, E2> repeat(final Function<E, Traversal<E, E2>> repeatTraversal) ...`

Thoughts?

**Comment by dkuppitz** [comment]
Afaik a function can't be inspected, hence you wouldn't be able to optimize it. With a traversal on the other hand you can turn ```g.V(1).repeat(_.out()).times(2)``` into ```g.V(1).out().out()``` and query optimizers can inspect the rolled out query.

> why does repeat need to start and end with the same type

I can't think of a use case where a different type would make sense. If the *sub-traversal* starts with a vertex, you would also expect a vertex in the first repetition, no? A different type would lead to an invalid query:

```java
g.V().out().repeat(__.outE("knows")).times(2) // becomes...
g.V().out().outE("knows").outE("knows") // which makes no sense
```

**Comment by mpollmeier** [comment]
Re 2) sure that makes sense ;)

Re 1) storing it as a GraphTraversal for optimisation makes sense, but we can still make it more straightforward (without `__`) for the user if we ask them to provide a function - and then simply call that function with our anonymous GraphTraversal. Here's a (slightly simplified) version of what I've done in Gremlin-Scala - the same should be possible in Java:

```
def repeat(repeatTraversal: GremlinScala[End] ⇒ GremlinScala[End]) = 
  GremlinScala[End](
    traversal.repeat(
      repeatTraversal(
        GremlinScala(AnonymousGraphTraversal.Tokens.__.start())
      ).traversal
    )
  )
```

usage: 
```
gs.V(1).repeat(_.out).times(2)
//equivalent to:
gs.V(1).repeat { repeatTraversal => repeatTraversal.out }.times(2)
```

https://github.com/mpollmeier/gremlin-scala/blob/master/src/main/scala/com/tinkerpop/gremlin/scala/GremlinScala.scala#L199-L204

For Gremlin-Scala I'm happy now, so we can close this issue if you like - but maybe you want to steal that pattern for Gremlin-Java.

**Comment by dkuppitz** [comment]
@okram may correct me, but I think another reason (maybe the main reason) was, that a function / lambda expression can't be (de)serialized, which is necessary for OLAP.

**Comment by okram** [comment]
@mpollmeier  -- for #1, `__` isn't typed because its an enum. However, that was not the original reason. The original reason was `g.<Vertex>of()` was required in Gremlin-Java each time the internal anonymous traversal was required. It was ugly and it didn't provide any real gain as typing the start doesn't effect which methods are possible. The super benefit was then we could also do `__`.

For #2, as Daniel says -- you can't repeat on something that is not the same start as end.

Finally, we could do `{t -> t.out}`, but there is no reason to..... `__.out` is much shorter. Think about `match()`-step.

```java
g.V().match('a',
  {t -> t.as('a').out().as('b')},
  {t -> t.as('b').in().as('c')})

--vs--

g.V().match('a',
  __.as('a').out().as('b'),
  __.as('b').in().as('c'))
```

**Comment by mpollmeier** [comment]
@okram I thought that Java 8 might have had a similar shortcut syntax like `_.out` - fair enough. 
Another argument for the above is that you get type safety: the user is forced to provide a `Traversal<E,E>`, whereas with `__` they can provide anything and it will compile, but fail at runtime. 

@dkuppitz while the user needs to provide a lamda the above code instantly creates a GraphTraversal (by calling `repeatTraversal(__)`, which is the same end result, so it should be able to get serialised just fine.

**Comment by mpollmeier** [comment]
Don't get me wrong, I have no problem with whatever way you choose to use in Gremlin-Java.
