### ISSUE TITLE
Migrate IO, Server, and Driver docs to use TinkerFactory.createModern()

### ISSUE THREAD

**Issue by okram** [tinkerpop/tinkerpop3#473]
There are a few bugs in I/O docs where the `g.io().blah()` methods don't exist.
Next, I migrated everything else over to use "modern" (including updating images to have vertex labels). 
I notice that server uses `TinkerFactory.createClassic()`. Be nice to have all those examples migrated over to using "modern". Should be easy, just I don't know the `.yaml`-stuff to use.

**Comment by spmallette** [comment]
think this is all good now...done.
