### ISSUE TITLE
.nextOrElse(Object)

### ISSUE THREAD

**Issue by mbroecheler** [tinkerpop/tinkerpop3#475]
Would be nice to have a .next() method that will return the provided value if the pipeline is empty.
Now, that you have to retrieve vertices via ```g.V(id).next()``` it would be nice to allow a null value return instead of throwing an exception: ```g.V(id).nextOrElse(null)```. There are probably other use cases.

**Comment by dkuppitz** [comment]
+1

We already have it for graph variables:

```
gremlin> g.variables().set('creator','daniel')
==>null
gremlin> g.variables().get('creator')
==>Optional[daniel]
gremlin> g.variables().get('creator').orElse('marko')
==>daniel
gremlin> g.variables().get('user').orElse('marko')
==>marko
```

So, to be consistent, it would be better to either change the return type of ```.next()``` to ```Optional<T>``` or introduce a new ```.get()``` method for this case:

```
gremlin> g.V().has("name","hercules").out("mother").out("mother").values("name").
gremlin>     next().orElse("anaxo")
==>anaxo
gremlin> g.V().has("name","hercules").out("mother").out("mother").values("name").
gremlin>     get().orElse("anaxo")
==>anaxo
```

**Comment by okram** [comment]
This is very doable, though I would not add a method called `nextOrElse()` (as then there are a bunch of other "optional"-type methods people will want --- see http://docs.oracle.com/javase/8/docs/api/java/util/Optional.html). Instead, we just need one method that returns a Java8 `Optional`. I think this is what @dkuppitz is saying with `Traversal.get()`. The problem with `get()` is that it is used in meta-programming to a great extent and I would hate to have it complicate features we want to add to Gremlin Sugar. Perhaps one of the following is a better name:

```java
Optional<E> Traversal<S,E>.asOptional()
Optional<E> Traversal<S,E>.optional()
Optional<E> Traversal<S,E>.tryNext()
Optional<E> Traversal<S,E>.nextOptional()
Optional<E> Traversal<S,E>.optionalNext()
Optional<E> Traversal<S,E>.findNext()           // findAny() -> Optional is used in the Stream API.
```

I'm leaning on `tryNext()` ?? Finally, adding this is trivial. It would be a default method on `Traversal<S,E>` and would simply be:

```java
public default Optional<E> tryNext() {
  return this.hasNext() ? Optional.of(this.next()) : Optional.empty();
}
```

**Comment by dkuppitz** [comment]
```.optional()``` is my favorite in the list, but it may confuse people who still know ```.optional()``` from Gremlin2. Thus ```.tryNext()``` seems to be a good choice.

**Comment by okram** [comment]
Ah. Good point. And we may add `optional()` as a step at a later date. I will go with `tryNext()` for now. If @mbroecheler has a better term, we can rename it easily.

**Comment by mbroecheler** [comment]
```tryNext()``` is fine by me.
