### ISSUE TITLE
Consider adding labeled step

### ISSUE THREAD

**Issue by BrynCooke** [tinkerpop/tinkerpop3#483]
Filtering by label is such a common thing people will want to do even for vertices.
So instead of:
```
g.V().has(T.label, "person")
```
use
```
g.V().labelled("person")
```

Also consider removing:
```
   public default GraphTraversal<A, A> has(final String label, final String key, final Object value)
    public default GraphTraversal<A, A> has(final String label, final String key, final BiPredicate predicate, final Object value) 
```
as these can be represented as:
```
g.V().labelled("person").has('name",  "marko")
g.V().labelled("person").has('name",  Compare.eq, "marko")
```

**Comment by rjbriody** [comment]
+1 although I think I would prefer the name ```hasLabel```.

As I've watched people transition to TP3, I've noticed that there is an assumption that Labels are special, and people seem surprised by the use of ```has(T.label, "")```.

Bob

**Comment by okram** [comment]
First, we would do US english and have it `g.V().labeled('person')`. :) However, I'm wondering if we should do something like `g.V().isA('person')` and `g.V().isNotA('person')`. ?

**Comment by BrynCooke** [comment]
Throw this one open to the floor. I am good with isA or hasLabel. Now not keen on labeled, and not just because of the spelling.

**Comment by dkuppitz** [comment]
Now that we have ```.is()``` we could add a special case:

```groovy
g.V().is('person')
```

It's trivial, something like:

```java
this.setPrdicate(traverser -> {
    final Object obj = traverser.get();
    final boolean checkLabel = obj instanceof Element && value instanceof String;
    return predicate.test(checkLabel ? ((Element)obj).label() : obj, value);
})
```

?

**Comment by BrynCooke** [comment]
Thinking about this last night and I think that people have to make a cognitive leap to go from label to is.

If 'label' was changed to 'type' then I think 'is'or 'isA' would be perfect. Otherwise I like the symmetry of 'hasLabel'

**Comment by okram** [comment]
How about:

`g.V().hasLabel('person', 'animal', 'thing')`

..getting translated to:

`g.V().has(T.label,Contains.within,Arrays.asList('person','animal','thing'))`

Or, if the user provided one label, then:

`g.V().has(T.label,'person')`.

This is easy to do as its not a step, but a `GraphTraversal` method that calls the respective `has()` method.

**Comment by dkuppitz** [comment]
:+1:

**Comment by BrynCooke** [comment]
+1
