### ISSUE TITLE
Generate helpful error when using store() as if it were TinkerPop 2

### ISSUE THREAD

**Issue by rjbriody** [tinkerpop/tinkerpop3#485]
Version: M6

If you attempt to use ```store()``` as it functioned in TP2 then you get a very unhelpful exception:

```
gremlin> list = []; g.V().store(l)
java.lang.ArrayIndexOutOfBoundsException
Display stack trace? [yN] y
java.lang.ArrayIndexOutOfBoundsException
```

note that I requested a stack trace but did not get one. I'm surprised I didn't get a "No signature method" error.

**Comment by okram** [comment]
What is "l" ? ............ You should get this error:

```
gremlin> list = []; g.V().store(l)
No such property: l for class: groovysh_evaluate
Display stack trace? [yN]
gremlin>
```

**Comment by dkuppitz** [comment]
That's what's meant:

```
l = []; g.V().store(l)
```

Anyway, it seems like Groovy converts the list to something else. Usually ```.store()``` shouldn't accept a list at all in Gremlin3. The behavior is pretty weird, it changes with a pre-filled list:

```
gremlin> l = []; g.V().store(l)
0
Display stack trace? [yN] y
java.lang.ArrayIndexOutOfBoundsException: 0
...
gremlin> l = [g.V(1).next()]; g.V().store(l)
No signature of method: com.tinkerpop.gremlin.process.graph.util.DefaultGraphTraversal.store() is applicable for argument types: (java.util.ArrayList) values: [[v[1]]]
Possible solutions: sort(), sort(java.util.Comparator), sort(groovy.lang.Closure), clone(), toSet(), size()
Display stack trace? [yN] N
```

**Comment by rjbriody** [comment]
That's right. I accidentally copied the wrong example, but Daniel explained it correctly.

**Comment by okram** [comment]
I think this is a Groovy console thing.... its trying to coerce the list in some way.. I don't know why. closing. please reopen if you have a solution.
