### ISSUE TITLE
multi-property filtering on value

### ISSUE THREAD

**Issue by BrynCooke** [tinkerpop/tinkerpop3#497]
I want to get the user where ts is 300, but I can't see a way of doing this at least with M6.
```
v1 = {
ts:[
100 @user:"u1",
200 @user:"u2",
300 @user:"u1" <-- I want this.
]
}
```

The best I could come up with was:
```
v1.properties("ts").filter(p->100 == (long)((Property)p.get()).value()).properties("user").value().next()
```
But having to use a filter isn't great especially with all the casting. Be good if I overlooked something though.
What I would like is:
```
v1.properties("ts").hasValue(100).properties("user").value().next()
```
I guess most of the `has*` methods should also have the equivalent `hasValue*` method on property traversals otherwise multi-properties will be difficult to query.

**Comment by dkuppitz** [comment]
If you just don't like ```.filter()```, here's how you can do it without using it:

```groovy
gremlin> g = TinkerFactory.createTheCrew()
==>tinkergraph[vertices:6 edges:14]
gremlin> g.V(1).withSideEffect("location", {"brussels"}).properties("location").as("x").
                value().retain("location").back("x").properties("startTime").value().next()
==>2004
```

And if we can get ```.has(traversal)``` working, it would be:

```groovy
gremlin> g.V(1).withSideEffect("location", {"brussels"}).properties("location").
                has(__.value().retain("location")).properties("startTime").value().next()
==>2004
```

However, I agree that a single method like ```.hasValue()``` would be really useful for this case.

**Comment by dkuppitz** [comment]
Dah, nevermind, I just realized that it is already possible:

```groovy
gremlin> g.V(1).properties("location").has(value, "brussels").
                properties("startTime").value().next()
==>2004
```

**Comment by BrynCooke** [comment]
That's three people that didn't know this without having to think..... Is the T.* class really a good idea?

It could be worth modifying the docs to say T.value rather than just value. Most devs will read that as a variable rather than an enum and it is not obvious that T.* is imported automagically. Possibly the groovy shell should only import T rather than T.* . The intent of the example code will become easier to spot with the added context.

**Comment by BrynCooke** [comment]
Closing in favour of https://github.com/tinkerpop/tinkerpop3/issues/499
