### ISSUE TITLE
Consider adding dedicated PropertyTraversal interface

### ISSUE THREAD

**Issue by BrynCooke** [tinkerpop/tinkerpop3#499]
Reasoning behind this is detailed in https://github.com/tinkerpop/tinkerpop3/issues/497
Three of us got this wrong with the other folks being much better at gremlin than I. Therefore users will also stumble at this.

If you're traversing a property then instead of using:
```
g.v().properties("foo").has(T.value, "prop")....
```
if would be nicer if you could use 
```
g.v().properties("foo").hasValue("prop").... //or any other has signature
```
If you are using an IDE then the code completion will give you the answer without having to resort to the docs.

**Comment by BrynCooke** [comment]
I think the functionality for this could be entirely expressed as defender methods.

**Comment by okram** [comment]
We can do a `hasValue()`, `hasKey()`, `hasId()`, `hasLabel()` if people want.... @dkuppitz @rjbriody  --- they will just be redirects to `has(T...)`.
