### ISSUE TITLE
Handle nested traversals when profiling

### ISSUE THREAD

**Issue by rjbriody** [tinkerpop/tinkerpop3#505]
As of right now, only root traversal steps are profiled. Need to revisit the ProfileStrategy and handle nested traversals when the implementation of nested traversals is complete.

**Comment by okram** [comment]
Nested traversal implementation is complete. Here are some classes that may help you.

`TraversalHelper`
`TraversalMatrix`

Note that a `Traversal` is a "child" if `Traversal.getTraversalHolder()` does NOT return `EmptyStep`. Next, a `Step` can implement `TraversalHolder` and you can walk down the tree.

**Comment by okram** [comment]
@rjbriody how are we doing on this front?

**Comment by rjbriody** [comment]
I have not looked at it at all yet.

**Comment by mbroecheler** [comment]
@rjbriody @okram It's great that we have anticipated this development in profiling by allowing nested profile information.

**Comment by okram** [comment]
I think this is done. If not, please reopen.
