### ISSUE TITLE
Single argument handling for except/retain

### ISSUE THREAD

**Issue by dkuppitz** [tinkerpop/tinkerpop3#508]
This works:

```groovy
gremlin> g.V().values("age").except(29)
==>27
==>32
==>35
```

This doesn't:

```
gremlin> g.V().values("name").except("marko")
The step with label marko  does not exist
Display stack trace? [yN] N
```

That means a String value is always treated as a step name. Can we use a fallback (treat String value as value in case a step with the given name does not exist)?

**Comment by okram** [comment]
Closing as this leads to "ambiguous method" definition.
