### ISSUE TITLE
Filter steps for scalar values

### ISSUE THREAD

**Issue by dkuppitz** [tinkerpop/tinkerpop3#510]
```gt```, ```gte```, ```lt```, ```lte```, ```eq``` and ```neq``` would be some nice additions to filter numerical values directly (```eq``` and ```neq``` not only for numerical values).

Most common use case:

```groovy
g.V().has(__.out('created').count().gte(2)).values("name")
```

And just in case it's not obvious, those steps should be chainable:

```groovy
g.V().has(__.out('created').count().gte(2).lt(5)).values("name")
```

**Comment by okram** [comment]
I was thinking about this while walking and think that we might overwhelm ourselves with method names. Thing `contains`, `incr`, `decr`, and any other thing we come up with. What about a step that takes a predicate, bipredicate, comparator, etc. For instance:

```groovy
g.V().has(__.out('created').count().given(gte,2)).values('name')
g.V().has(__.out('created').values('name').given(eq,'ripple')).values('name') 
g.V().has(__.out('created').values('name').given(contains,['ripple','lop','gremlin'])).values('name') 
```

In essence, the object of the traverser is the first argument of the bi-predicate. The bi-predicate and second argument are arguments to `given()`.

Now, `given()` is alot like `by()` except that `given()` is a filter modulation, where `by()` is an map modulation. 

Better names than given?
  . `suchThat()`
  . `where()`
  . `iff()` // if and only if
  . `assuming()`
  . ... ?

Thoughts?

**Comment by dkuppitz** [comment]
Yea, I've actually had that in mind, too. Simply forgot to mention it. I thought ```.is()``` would make a good step name.

```groovy
g.V().has(__.out('created').count().is(gte,2)).values('name')
g.V().has(__.out('created').count().is(2)).values('name') // same as .is(eq, 2)
```

**Comment by rjbriody** [comment]
I like "where".

Bob

**Comment by dkuppitz** [comment]
```where``` is already in use for ```match``` and ```select```. Might be too many overloads then.

**Comment by dkuppitz** [comment]
Just another idea. We already have ```.retain()``` which means ```eq``` and we have ```.except()``` which means ```neq```. Both steps already accept scalar values. If we would add some method overrides that accept a (bi/tri/...)-predicate, your 3 aforementioned samples would be:

```groovy
g.V().has(__.out('created').count().retain(gte, 2)).values('name')
g.V().has(__.out('created').values('name').retain(['ripple'])).values('name') 
g.V().has(__.out('created').values('name').retain(['ripple','lop','gremlin'])).values('name')
```

The two latter would already work.

**Comment by okram** [comment]
I really like your realization of retain/except, but I just don't like the terminology "except"/"retain" in this situation............................

**Comment by dkuppitz** [comment]
Yea, you can have ```.retain(eq, 2)``` and ```.except(neq, 2)``` which is the same thing. Maybe it's all just ```.has()```..?

**Comment by dkuppitz** [comment]
Here it ```.is()```: http://www.tinkerpop.com/docs/3.0.0-SNAPSHOT/#is-step
