### ISSUE TITLE
ResultSet.all seems deadlock prone

### ISSUE THREAD

**Issue by nik9000** [tinkerpop/tinkerpop3#515]
ResultSet.all returns a CompleteableFuture that blocks on the worker pool until isExausted returns false.  isExausted in turn needs a thread on the worker pool to even return.  So its totally possible to consume all threads on the worker pool waiting for .all to finish such that you can't even get one to wait for isExausted to run.

**Comment by spmallette** [comment]
Good analysis - thanks.   I seem to have a test that replicates the situation.  I basically give the driver two workers and then issue two long run scripts for Gremlin Server to process - those driver workers get stuck WAITING around `isExhausted` and the driver doesn't seem to be able to get out of that state.  Trying to sort out a solution now.

**Comment by spmallette** [comment]
I think I have this fixed now - assuming I properly replicated the problem with my test which was failing and is now passing.  Please feel free to re-open if I've missed something somehow.  This was a nice find - thanks again for pointing it out.

**Comment by nik9000** [comment]
Thanks for fixing it!  I think your recreation matches my experience.
