### ISSUE TITLE
Consider making edges immutable

### ISSUE THREAD

**Issue by BrynCooke** [tinkerpop/tinkerpop3#518]
Currently TP has mutable edges.

Discussions in https://github.com/tinkerpop/tinkerpop3/issues/489 indicate that this may not be a good idea.

Most SQL developers coming to TP will think that edges are equivalent to junction tables and therefore choose a bad design for their graph.

Also a history strategy becomes difficult to implement if edges are mutable.

Thoughts?

**Comment by okram** [comment]
You mean: Once the edge is defined (with properties and all), it can not be updated? I don't think this is necessary at the TP level. In Titan (e.g.), edges are immutable. When you update an edge, it creates a new edge behind the scenes. Thus, every update is a new edge, but to TP, it looks like the same edge.

Thoughts?

**Comment by mbroecheler** [comment]
@BrynCooke I understand where you are coming from, but I don't think we necessarily need to take the conclusion of #489 that far. I think it is important to consider edges as atomic data elements but that does not necessarily mean we need them to be immutable. It's like a row in an RDBMS table - you can update the columns but you think of it as one row with one access level, one provenance record, etc.

**Comment by okram** [comment]
Going to close this as this is a vendor specific issue and not something we should require of TinkerPop. Open it back up if there is an argument against the case.

**Comment by BrynCooke** [comment]
I agree.
Thinking about it a future history strategy can take the same approach to edge versioning. Any edge mutation results in a new edge followed by marking up the old edge with a removed timestamp.
