### ISSUE TITLE
Create a Meta-Edge strategy to ship with TP3

### ISSUE THREAD

**Issue by davidcrouch** [tinkerpop/tinkerpop3#523]
Can't think of a better name but it essentially is a graph strategy that supports edges with meta-properties. As to not offend it could be named differently to support a different concept e.g. relationship = like an edge but with meta-properties (and multi-properties). 

This is an abstraction of #519 and #520. I have a need for #519 and #520 but am concerned a generic implementation may not support my specific needs. However, from discussions with @BrynCooke it seems that both he and I are implementing versions of #519 and #520 with the common denominator being the requirement of meta-properties on edges (or equivalent i.e. represented as a vertex - see #489 discussion.

**Comment by mbroecheler** [comment]
So, you basically mean a strategy that would expose vertices as higher-order edges and could also accommodate hyper-edges in this way?
Would that be a graph strategy or would that be a custom traversal @okram? I always confuse what is for what.

**Comment by okram** [comment]
This would be a Traversal DSL and the objects would be like `HyperEdge`, etc. I wouldn't go down that road just yet... though you can always experiment and tell us how it goes.

Next, we won't support this in TP3 as its "too much." More features, more to maintain and I don't think we want users to start thinking in terms of hyper-graphs.

**Comment by davidcrouch** [comment]
I agree it's probably too much for TP3 and probably shouldn't be part of the the core product. But there is a real need and there is some confusion on how to implement it using the new TP3 tools. It would be beneficial of trying something even as a test of the extensibility of TP3 i.e. it could be a by-product of doing that exercise.

I have been experimenting with it and trying this:-

1) enhance standard DSL using "of" 
2) add custom DSL using "of"
3) extend GraphTraversal to override standard methods e.g. outE
4) extend GraphTraversal to add a new concept e.g. outR  ("R" being a "relationship" concept - looks like an edge but is really a vertex underneath).

I think it may be more than a traversal DSL. I think there is a need for overloaded methods to store the meta-properties on the "edge" (or do some mapping) and hence requires a graph strategy as well. 

I will keep you posted but I am at my limit with TP3 knowledge and Java skills. I took 10+ years off of programming so I have another challenge of getting over some of the gotchas with Java generics.
