### ISSUE TITLE
Semantics of inside and outside

### ISSUE THREAD

**Issue by dkuppitz** [tinkerpop/tinkerpop3#527]
What does ```inside``` and ```outside``` in terms of ```gt```, ```gte```, ```lt```, ```lte``` mean? Any opinion is welcome.

The best real-world example that came to my mind were binary options. If you purchase a binary **inside** option, you get paid if the price is greater than the lower strike price and lower than the higher strike price (```gt``` AND ```lt```). If you purchase a binary **outside** option, you get paid if the price is lower than the lower strike price or greater than the higher strike price (```lt``` OR ```gt```).

In terms of ```.has()``` this is what I think it should be:

```groovy
.has('price', gt, lower).has('price', lt, higher) // inside
.union(__.has('price', lt, lower), __.has('price', gt, higher)) // outside
```

It would also be ok for me to use ```gte``` and ```lte```. What I don't like is a mix like in the current implementation of ```.between()```, which is ```.has('price', gte, lower).has('price', lt, higher)```.

**Comment by dkuppitz** [comment]
http://www.thefreedictionary.com/inside
> The part away from the edge; the middle part.

http://www.thefreedictionary.com/outside
> The space beyond a boundary or limit.

I think that nails it. ```inside``` is ```value > lower && value < higher``` and ```outside``` is ```value < lower || value > higher``` (as already mentioned in my initial post).

**Comment by okram** [comment]
I'm good with that.

**Comment by jimlloyd** [comment]
My intuition was that `inside` should use `lower <= value <= higher`, and `outside` should use `value < lower && value > higher`. This matches your proposed definition of `higher`, but is contrary for your definition of `lower`. After seeing that Marko agreed with your proposal, I almost decided to simply remain silent and let the proposal stand unchallenged, as at first I couldn't think of any justification for my intuition. 

But then this idea occurred to me, which you are of course free to ignore: Suppose in addition to `.is()` you also included `.isnot()`, which simply negates the truth value of the predicate. If you have .isnot(), then wouldn't you want `.is(inside, [a,b])` to have the same effect as `.isnot(outside,[a,b])`?

**Comment by dkuppitz** [comment]
Yea, I was waiting for someone to point that out. Marko and I discussed opposites earlier this night and you're right - ```inside``` is not the opposite of ```outside```, but on the other hand they're semantically correct. That bothers me, as my initial argument was

> Don't use ```between``` for the predicates, there's no opposite for it. Let's use ````inside``` and ```outside``` instead.

Now we still don't have a opposite :). I think I like your proposal to catch the boundary with the ```inside``` predicate.

**Comment by dkuppitz** [comment]
@jimlloyd I've added (not yet pushed) a ```Range``` class that allows you to define whether you want an inclusive or an excusive range.

```groovy
gremlin> import static com.tinkerpop.gremlin.process.util.Range.*
...
gremlin> __.inject(1,2,3,4,5).is(inside, inclusive(2,4))
==>2
==>3
==>4
gremlin> __.inject(1,2,3,4,5).is(inside, exclusive(2,4))
==>3
gremlin> __.inject(1,2,3,4,5).is(outside, exclusive(2,4))
==>1
==>5
gremlin> __.inject(1,2,3,4,5).is(outside, inclusive(2,4))
==>1
==>2
==>4
==>5
gremlin> __.inject(0,1,2,3,4).range(inclusive(0l,3l))
==>0
==>1
==>2
==>3
gremlin> __.inject(0,1,2,3,4).range(exclusive(0l,3l))
==>1
==>2
```

WDYT?

**Comment by dkuppitz** [comment]
From @rjbriody:

> i'm just thinking that u want to specify the incl/excl operator on each value like:
> inside(gte, minValue, lt, maxValue)
> then i was thinking, what if it was just a range step?
> range(lt, minValue, gt, maxValue) for outside
> range(gte, minvalue, lte, maxValue) for inside

Then I remembered the latest changes for ```order()``` and I think we can apply the same pattern here:

```
gremlin> __.inject(0,1,2,3,4).range(local).by(incl, 0).by(excl, 3)
==>0
==>1
==>2
```

Thoughts?

**Comment by okram** [comment]
Couple of things:

range(local) would operate on the current object, thus, 0, then 1, then 2.... if the injected object was a list, then range(local) would make sense as it would range over the list (or map). Which we should add!

next, I think excl and incl is just getting too much. too much stuff.... if you want to include or exclude, just increment or decrement your provided value to range by 1.

next, groovy has a Range object [0..<1] or [0..1] ... so this sorta already exists in Gremlin-Groovy.

**Comment by dkuppitz** [comment]
Ok, local changes reverted. Will use the semantically correct versions. For any specific needs you can still use two chained ```.is()``` steps.
