### ISSUE TITLE
Incomplete serialization of error responses in HTTPGremlinEndpointHandler.java

### ISSUE THREAD

**Issue by bdmcbri** [tinkerpop/tinkerpop3#528]
In HTTPGremlinEndpointHandler.java, error responses may not be valid JSON because of control characters, newlines, etc, in the message passed to sendError(..).

**Comment by spmallette** [comment]
do you have an example?

**Comment by spmallette** [comment]
Made some adjustments here.  Used the Jackson `ObjectMapper` to generate the JSON string rather than just via manual construction.  That should fix the problem.
