### ISSUE TITLE
Remove Neo4jGraphTraversal.

### ISSUE THREAD

**Issue by okram** [tinkerpop/tinkerpop3#529]
The only reason we need Neo4jGraphTraversal is cause of mid-traversal `cypher()`. Because of this, we have lots of overhead -- source code generation, some tests can't run because it method counts are off, etc. Also, lots of Neo4j code will go away .... e.g. Neo4jElementTraversal, Neo4jVertexTraversal, Neo4jGraphTraversals, Neo4jDefualGraphTraversal, Neo4jEdgeTravaersal, Neo4jVertexPropertyTraversal....

I'm wondering if we get rid of `g.V().out().id().cypher('MATCH...').select('a').outE()` in favor of JUST `g.cypher(MATCH).select('a')`. In short, `cypher()` is a method off `Neo4jGraph` and yields a `GraphTraversal`.

Thoughts?

**Comment by spmallette** [comment]
Well - what does this mean for vendors who might want to extend Traversal in some way with their own stuff?  will they just be stuck with the overhead?

**Comment by okram** [comment]
I dunno. I sorta don't think they should extend `GraphTraversal`. If they want their own thing, they create their own DSL.....

**Comment by spmallette** [comment]
code generation is rarely a good solution to anything and it's not a great thing for other vendors to use if they wanted to do something similar to what we had with cypher.  I guess I'm for making it work as you said in that sense.  let's get simple with it.  if we're going to do a feature takeaway - better to do it now before we release.
