### ISSUE TITLE
There are no lambdas. [proposal]

### ISSUE THREAD

**Issue by okram** [tinkerpop/tinkerpop3#531]
What if there was only `Traversal`. This would greatly reduce the complexity of many steps. No such thing as functions vs. traversals. What is `choose{it.name[0] == 'm'}` then? I'm glad you asked -- `choose(__.filter{it.name[0] == 'm'})`. People could write the lamda form (the first expression), but it is encoded as a traversal. The ONLY steps that actually take lambdas are the core steps -- `filter()`,`map()`,`flatMap()`,`sideEffect()`, and `branch()`. And with the power of `TraversalLambda` the need for those is quickly going away, Every other place there is a lambda, its actually a traversal rewritten in terms of filter(),map(), etc.

This would mean that there would be no concept of `FunctionHolder`. Just `TraversalHolder`s. No concept of if/else "is this by() a true function or a traversal function?". 

The theory then is Gremlin is an arbitrary nesting of `Traversals`. That is it.

**Comment by mbroecheler** [comment]
Love it. But I guess you knew that. From a database perspective, lambdas are nasty because you cannot optimize them. You have no idea what happens inside them. For all you know it could be ```Thread.sleep(AckermannFunction.compute(100))```.

You can always make the argument that you need lambdas for full generality, but with nested traversals their use cases are fairly limited.
Put another way: The more we force users to write traversals that we can inspect (and optimize) the better.

**Comment by spmallette** [comment]
:+1: - this is a good idea.  it's one of those changes where i know some good up front benefits we're going to get, but it makes me wonder just what kind of interesting things will come out of it that we haven't yet discovered.

**Comment by dkuppitz** [comment]
Note that there's at least one exception. The 3rd ```.by()``` in ```group().by().by().by()``` is always a lambda. A work around would be to pass in ```__.inject(resultOfSecondBy)```.

**Comment by dkuppitz** [comment]
Ha, nevermind, I just realized that it doesn't have to be a lambda, I acutally never tried that before.

```groovy
gremlin> g = TinkerFactory.createModern()
==>tinkergraph[vertices:6 edges:6]
gremlin> g.V().group().by(outE().count()).by()
==>[0:[v[2], v[3], v[5]], 1:[v[6]], 2:[v[4]], 3:[v[1]]]
gremlin> g.V().group().by(outE().count()).by().by(unfold().count())
==>[0:3, 1:1, 2:1, 3:1]
```

**Comment by okram** [comment]
Ha. Yea, I was reviewing the steps and was like "damn, 3rd lambda of `group()`." But sweet, `by(traversal)` converts it to a `TraversalLambda` so -- it works. Good realization.

I actually think this is going to take me maybe 3 hours to do. Been going over each step that will be effected and its pretty trivial.

The one outstanding thing I can't figure out is `BiFunction` steps. If we can interpret a `BiFunction` as a traversal then reductions like `fold()` and `sack()` will be traversal based. But what does that look like? `Traversal<Pair<A,B>,A>` -- gross.

**Comment by jbmusso** [comment]
Very nice development.

On a side note - this should also make it easier to build language bindings. When building Gremlin/Groovy strings from JavaScript environments (ie browsers/Node.js - not talking about nashorn here), getting a string representation of a lambda (ie `function() {}` in JavaScript) isn't easy (actually it's easy, but it needs to be transpiled to Groovy which is another story). gRex currently passes lambdas as strings (`'{...}'`) and handles them with regexp, which works to some extent for the most simple lambdas. The less lambdas, the better.

**Comment by spmallette** [comment]
if most traversals are now lambda free, it would seem that traversal serialization might once again make sense in the context of remoting them to Gremlin Server.

**Comment by okram** [comment]
Traversal serialization.... It COULD be possible. Realize that "no lambdas" doesn't mean that we don't use Java8 lambdas in our codebase. It would mean all the `list.stream().filter().map()` code would have to be gutted. It would mean all the `super.setPredicate()` code would have to be gutted. All the `list.forEach()`, etc. Its possible, just it would entail writing the steps in Java7-style and being hyper diligent about it moving forward (where diligence can be dictated by a test suite).

**Comment by okram** [comment]
...in short, no more "anonymous classes" (as that is ultimately what a Java8 lambda is).

**Comment by spmallette** [comment]
I didn't think it would be necessary to remove lambdas from the code base.  As long as that same code exists on the server as is on the client there shouldn't be a problem (i.e. gremlin-core would be in both places presumably).  What we couldn't do is serialize a traversal that contained a lambda as compiled in the console and then send that to the server for processing b/c the server doesn't know anything about that console compiled lambda.  However it does know about all the lambdas in our gremlin-core.  no?

**Comment by okram** [comment]
.............that is a good point. I actually don't think you are right though. The lambda on my JVM will be BranchStep$Function@232132. When it gets to another JVM, it won't know what it is... ??? Something we could test easily?

**Comment by okram** [comment]
If we can serialize traversals, I can guarantee "pure state" on the receiving side. All we have to do is `clone()` and then serialize. My `clone()` work is super consistent and clean throughout. I test its abilities in TinkerGraph 8 threads and Hadoop multi-JVM. And when I mess up a clone, its readily apparent.

**Comment by BrynCooke** [comment]
I had been thinking about this for a while and was wondering about using bytecode analysis on lambdas to check if they are 'self contained'. If they are then they can be serialized and sent across the wire.
If this was wrapped up in to a TraversalStrategy then it could tell which parts of the pipeline could be run across the wire and which parts have to be run locally.
