### ISSUE TITLE
values(...) should preserve the given order

### ISSUE THREAD

**Issue by dkuppitz** [tinkerpop/tinkerpop3#534]
If you provide i list of property keys for ```values()```, the order is not preserved. The result you get can be totally mixed up.

```groovy
gremlin> g.V(3).values("lang","name")
==>lop
==>java
```

Now I would expect that *lop* is the *lang* and *java* the *name*. **If** the order would be preserved, there would be an easy solution for the use-case described in #533.

The question is: Is there a reason why ```.values(...)``` doesn't care about the order?

**Comment by okram** [comment]
This is a really limited scenario What about:

```java
g.V.values("lang","name")
==>java
==>lop
==>bob
==>sam
```

Is bob the lang of sam? In other words, only in your particular single vertex example does it make sense, but once you get vertices that don't have all the properties or only some of them, the order goes out the window. Is it worth it to have `values()` be the only step that guarantees an order?

**Comment by dkuppitz** [comment]
The only use-case for this (so far) is #533. But - as usual - there are more ways to solve it, it's just more typing. So if you don't like to keep the order, just close the issue.

**Comment by okram** [comment]
`values()` is very similar to `outE`, `inE`, etc. If we make `values()` ordered, it would imply that `outE('knows','created')` would be ordered to -- i.e. all the knows and then all the created. Moreover, `values()` also has the problem that it could have multiple values for the same property.

```groovy
v.values('name','age')
==>marko
==>ma rodriguez
==>32
==>35
==>37
```

is `ma rodriguez` and age? As such, I think its best to not tell the user there is an order.........
