### ISSUE TITLE
SerializationTest#shouldSerializePath order dependency

### ISSUE THREAD

**Issue by MMcM** [tinkerpop/tinkerpop3#538]
This test, which I believe was added / changed recently by 8db2c9aaf66eecede2c90b0b53dc20a64ad4cc51 seems to rely on the first edge out from `marko` being `created` `lop`, rather than one of the `knows` ones. Is that a part of some contract that we've got wrong here?

**Comment by spmallette** [comment]
i keep getting bit on "order" when writing tests.  There is no intent to guarantee order.  gotta fix that.

**Comment by MMcM** [comment]
Would it be worth having a wrapper graph (around tinkergraph, say) that randomized traversals?

**Comment by spmallette** [comment]
hmmm....i'll think about it, but my initial thinking is that I'd rather not add that type of indirection - just gotta do a better job writing these tests.

**Comment by spmallette** [comment]
i think the above commit should fix this problem. how is your implementation coming along btw?
