### ISSUE TITLE
Should Traversers "short circuit" as() and back()

### ISSUE THREAD

**Issue by rjbriody** [tinkerpop/tinkerpop3#539]
Versions: 2.5.0 and 3.0.0.M6

It seems as though a "dead end" Traverser causes that Traverser to be removed from the Traversal when using ```as()``` and ```back()``` steps.

That's probably intractable, so here is an example (using TinkerGraph):

```
gremlin> g.V().as('roots')
==>v[1]
==>v[2]
==>v[3]
==>v[4]
==>v[5]
==>v[6]
gremlin> g.V().as('roots').out('knows').as('ignored').back('roots')
==>v[1]
==>v[1]
```

Note that ```v[1]``` is the only vertex with a 'knows' edge
```
gremlin> g.E().has(label, 'knows').outV()
==>v[1]
==>v[1]
```

So it appears as though Traversers who do not have a ```knows``` edge die at the ```out('knows')``` step even though that step comes after the ```as('roots')``` step. Is this to be expected?

**Comment by dkuppitz** [comment]
That is the expected behavior. In Gremlin2 we've had the ```.optional()``` step, but its implementation wasn't that pretty: https://github.com/tinkerpop/gremlin/issues/359

**Comment by okram** [comment]
Yes, this is a `back()` filter not an `optional()`. You are looking for `has(traversal)`.
