### ISSUE TITLE
[proposal] Do not expose filter{}, map{}, sideEffect{}, ... 

### ISSUE THREAD

**Issue by okram** [tinkerpop/tinkerpop3#540]
The other day, @mbroecheler said to me: "Why don't you just get rid of allowing lambdas at all in TP3?"

Now that all computation is in terms of `Traversal`, this would simply entail the following things:

  . No more `filter{}`, `map{}`, `flatMap{}`, `sideEffect{}`... the steps would still exist (for extension), but not exposed steps at `GraphTraversal`.
  . No more `by{}` both function and order.

Thats it.... at that point, there would be no lambdas in TinkerPop3.

While this is a 1 hour coding exercise, the ramifications are pretty intense. Please express your thoughts one way or the other.

**Comment by mbroecheler** [comment]
Pros:
+ You can fully optimize and rewrite the entire traversal which is great for graph db vendors and ultimately users because they get the best performance
+ Users won't do ``` .filter{ it.name == 'marko'}``` instead of the optimizable ```has('name','Marko')```
+ Lambdas are hard to do cross-platform
+ Lambdas are hard to do in client-server settings
+ Lambdas introduce security issues

Cons:
- We loose expressivity. However, I have yet to see a compelling use case that would be affected given the work Marko has done with nested traversals.

**Comment by davidcrouch** [comment]
The statements:- 

- "the steps would still exist (for extension)",  
- "Lambdas introduce security issues", and
- "I have yet to see a compelling use case that would be affected "

....are convincing enough for me.

**Comment by mhfrantz** [comment]
One of the appealing features of Gremlin is that it would allow us to incorporate application-specific data types.  For example, we could use java.net.InetAddress (or Guava's InetAddresses) to parse string representations of IP addresses, and then operate on the byte arrays that result (getAddress).  We want this to happen in the server in OLAP.  We could also write our own types that could encapsulate business logic, and make them available in the server runtime.

Do you foresee adding formal type extensibility?  As of now, the types that we are allowed to store are implementation-specific, so the technique of materializing objects within a traversal would be more portable.

I appreciate the concerns expressed in this thread, and anxiously await your decision.

**Comment by okram** [comment]
A simple "happy middle" solution to this problem is this:

`LambdaCheckStrategy`
     http://www.tinkerpop.com/docs/3.0.0-SNAPSHOT/#traversalstrategy

Vendors (or even TinkerPop3) can register this strategy by default if they don't want people using `map{}`, `flatMap{}`, etc. Basically, the `TraversalStrategy` looks for the use of lambda-steps (4-steps and two step modulators) in the submitted traversal and throws an `IllegalArgumentException` if it finds it. If someone wants to be hardcore and use lambdas, has user defined types, checks a REST service in a query, does some nasty mathematics in a traversal, wants to rely on user defined algorithms, etc., then they can simply `TraversalStrategies.getStrategies(Graph.class).removeStrategies(LambdaCheckStrategy.class)` and then they can use lambda steps. That line of code can be registered in your GremlinServer `yaml` or in your Java application as a `static { }`.

Thus, lambdas would be for hardcore users who have gotten past the basics of `g.V.has('name','daniel')` and realize that `g.V.filter{it.name == 'daniel'}` is not a smart thing to do.

The only drawback I see is that @spmallette is interested in moving back to being able to serialize traversals across the wire. We got rid of this and said: "Gremlin-Java8 traversals do not go over the wire -- only ScriptEngine-based Gremlin variants allowed." But without lambdas, it *may* be possible to move back to serialized Gremlin-Java8 traversals. The hardcore lambda users would have to use Gremlin-Groovy (etc.) in such situations.

**Comment by okram** [comment]
This was trivial to implement. It was so easy I was confused for a bit and was like: "this has to be harder..." --- I started going down this crazy path __trying__ to make it more than it was. Ended up realizing it was really that simple. Here it is in action:

```java
gremlin> import org.apache.tinkerpop.gremlin.process.traversal.strategy.optimization.*
==> ...
gremlin> g = graph.traversal(standard(LambdaRestrictionStrategy.instance()))
==>graphtraversalsource[tinkergraph[vertices:6 edges:6], standard]
gremlin> g.V().has('name','marko')
==>v[1]
gremlin> g.V().filter{it.get().value('name') == 'marko'}
The provided traversal contains a lambda step: LambdaFilterStep(lambda)
Display stack trace? [yN]
gremlin> g.V().as('a').out('knows').as('b').select().by('name')
==>[a:marko, b:vadas]
==>[a:marko, b:josh]
gremlin> g.V().as('a').out('knows').as('b').select().by{it.value('name')}
The provided traversal contains a lambda traversal: lambda
Display stack trace? [yN]
gremlin>
```
