### ISSUE TITLE
static code analysis

### ISSUE THREAD

**Issue by dkuppitz** [tinkerpop/tinkerpop3#542]
Run a static code analysis and (primarily) get rid of all performance issues.

Document changes by running ```TinkerGraphTest.benchmarkStandardTraversals``` periodically (at least one time prior any optimization and one time when all optimizations are done).

**Comment by spmallette** [comment]
Any reason to not make this benchmark part of the standard performance test suite using the existing benchmark api?

**Comment by spmallette** [comment]
After some separate talks with @dkuppitz -  he's going to do this one via #231 which should close these out together.
