### ISSUE TITLE
Abstraction layer for indexing and constraints

### ISSUE THREAD

**Issue by nik9000** [tinkerpop/tinkerpop3#544]
It looks like adding indexes and constraints (like Titan's set properties) is backend dependent.  It'd be cool to have an abstraction on top of that.  I imagine it'd need something similar to Graph.Features....

**Comment by spmallette** [comment]
A long time ago, we made the conscious decision not to include this in TP3.  We had a simple version of this in TP2 and it didn't work so well.  We understand that not having this feature creates situations where you don't get completely vendor agnostic code, but we've also found the indexing/schema capabilities of various graphs to be so different in terms of complexity and capability that you end up forcing users into the native APIs anyway.  

I'm going to close this as I don't think we will consider changing from this direction.  If you have some ideas around how this feature might be done well, please feel free to share them on the apache dev mailing list to see what kind of discussion it generates.  Thanks.

**Comment by nik9000** [comment]
Fine by me.  I certainly can't think of any good way to do it.  I imagine we'll end up with some abstractions for just this on the client side before too long.  Maybe then I'll be able to talk more intelligently about it.   I'll go to the mailing list then.

**Comment by spmallette** [comment]
In TP2, I typically did something where I had a "Schema" class with an `init` method...In that class, I would do some detection of the type of `Graph` instance given to the `init` and then write my native indexing/schema code there.  If you only need to support that for a small handful of implementations then that might be good enough.  If you have lots to support, then a whole abstraction layer on that side might be needed as you described.
