### ISSUE TITLE
Add an addEdge default method.

### ISSUE THREAD

**Issue by okram** [tinkerpop/tinkerpop3#547]
We should add:

```java
Vertex.addEdge(String edgeLabel, Iterator<Vertex> vertices, final Object... keyValues)
```

...that allows for this:

```groovy
marko.addVertex('worksFor',g.V.has('name',within,['lanl','aurelius','datastax','at&t']))
```

**Comment by dkuppitz** [comment]
Start with the traversal and you can do it with the current set of steps:

```groovy
g.V.has('name',within,['lanl','aurelius','datastax','at&t']).as('x').
    map {marko}.addOutE('worksFor','x')
```

And in those cases where it's really just an iterable (e.g. a list), you can start your traversal with ```.inject()```. The key is to map the last element to the vertex you want to connect.

**Comment by spmallette** [comment]
I don't know if this raises an interesting question or not, but daniel's point made me wonder about the philosophy of the Gremlin API.  In cases like this, how do we decide between a "structure" solution or a "process" solution?  Is the philosophy to prefer structure to process when:

1. no approach in process exists that can accomplish the same thing OR
2. there is the possibility that a performance gain can be realized

Is that a fair way to describe a way to help guide such decisions?

**Comment by okram** [comment]
I think we need to get our CUD better in Gremlin process. In fact, I don't even like `g.addVertex()` and `v.addEdge()`. To @spmallette, I think these methods stay as they are like the `Iterators` class -- core vendor methods, but I think for Gremlin traversals, we need better create, update, delete that are not so Java-ish and don't rely on `sideEffect{}`.

**Comment by dkuppitz** [comment]
For the traversal side: ```.addV()``` has been discussed in #479. The problem with with the current implementation of ```.add[In|Out|Both]E()``` is that it doesn't support a weight property. Problematic use-case:

```groovy
// assume marko also created ripple
g.V(1).next().addEdge("created", g.V(5).next())

// now let's create some co-worker edges
g.V().as("a").out("created").in("created").except("a").addInE("co-worker", "a")
```

The last query would create 2 co-worker edges between marko and josh (actually 4, 2 in each direction). Gremlin2/Faunus had the option to specify a weight-property, which - in the aforementioned scenario - would lead to a single edge being created between marko and josh with a weight of 2.

Afaik we never wrote that down before, so that's just a summary of what we have to work on.

**Comment by okram** [comment]
Here are patterns I would like to see:

```groovy
g.V.out.addOutE('knows',vertices,keyValues...)  // add edges to Iterator<Vertex>
g.V.as('a').out.addInE('created','a',keyValues...) // add edges to 'a' labeled vertex
g.V.property(key,value) // add property to vertex
g.V.out.coalesce(has('name','stephen'),addV('name','stephen')) // @dkuppitz coalesce use of addV
```

*Questions*: Are these `sideEffect()`-steps in that they DO NOT return the thing they just created? Do we treat these like we treat `remove()` and make them "terminal steps" in that no new steps can be added and they return `void`? The problem with BOTH of the above (non-sideEffect and `void`) is then the 4th example is not possible.

*Answers*: The funny thing is that the object they create allows you to get back to where you were and are thus not "stream altering" sideEffects in the sense like `groupCount`, `group`, etc. For example, `g.V.addOutE('knows',bob).inV` gets you back to the original `v`. Thus, having `GraphTraversal<Vertex,Edge> addEdge(...)` is not a bad thing. In this way, they are `map()`-steps.

I suppose the final problem is "weight"-property for edges. We do get `Traverser.bulk()` but we don't know if thats the total bulk arriving unless a barrier step is prior. Doing a barrier is computationally expensive. And once we have the bulk, what is the actual "weight" ? Some function of the bulk -- what function? -- e.g. bulk / someOtherProperty. ?? Lambda? Perhaps we only support:

```
addOutE('knows',vertex,'since',2012,'weight',T.bulk)
```

Finally, it might be smart to demand a prior barrier to ensure that you have all the traversers that will be at the vertex at that moment..........

**Comment by dkuppitz** [comment]
Almost full ack, but IMO the first traversal in

```groovy
g.V.out.addOutE('knows',vertices,keyValues...)  // add edges to Iterator<Vertex>
g.V.as('a').out.addInE('created','a',keyValues...) // add edges to 'a' labeled vertex
```

is over-complicated. Why? Because it can be done like in the second traversal, all you need is a ```flatMap()```:

```groovy
g.V.out.as('a').flatMap(vertices).addInE('knows','a',keyValues...)  // add edges to Iterator<Vertex>
```

**Comment by okram** [comment]
Yea, but that is intense if the user has to know about `flatMap` and to know how to use it like an 'inject'. Even took me a while to realize "the trick."

What about `addE` taking an anonymous traversal?

```groovy
g.V.has('name','lop').in('created').
  addOutE('collaborator',
               as('x').out('created').has('name','lop').in('created').except('x'))
```

Now, lets say you have direct vertex reference pointers, then its:

```
g.V.has('name','lop').in('created').addOutE('manager',inject(v1))
```

Now, I'm using `inject()` wrong. I think we need another step that is "hard start" like perhaps `__.start(object...)` or `__.__(object...)`, then its just `addOutE('manager',__(v1))`.

**Comment by dkuppitz** [comment]
```__.start(object...)``` or ```__.__(object...)``` or whatever you want is just ```map()``` for a single element or ```flatMap()``` for multiple elements / iterators. Since it's varargs I guess it's always ```flatMap()```. The point is, we don't need a new step to get the job done. Agree?

**Comment by okram** [comment]
Okay. I'm not a fan of using map/flatMap, but okay. I think the more pressing concern right now is, does `addE` have two signatures -- one that takes a as-label and the other taking an anonymous traversal. ??

**Comment by dkuppitz** [comment]
Since you want to hide ```map```/```flatMap``` from the user, yes, we should provide 2 signatures.

**Comment by okram** [comment]
Next: do they return the object they created?

**Comment by dkuppitz** [comment]
Yes, definitely. If it were sideEffects, you would have trouble to find the newly created element in some scenarios.

**Comment by okram** [comment]
so `addV()` is weird in that for each object that touches it, the "same" vertex gets added!

**Comment by okram** [comment]
its like:

 * each `addE()` should have a `barrier` before it.
 * each `addV()` should have a `fold` in front of it.

**Comment by dkuppitz** [comment]
> so ```addV()``` is weird in that for each object that touches it, the "same" vertex gets added!

If you don't want that behavior, you can use the ```getOrCreate``` pattern (```.coalesce(<get-traversal>, addV(...))```). However, that might not work in OLAP when multiple threads come into play. Even worse in distributed systems.

**Comment by okram** [comment]
Thus, `addE()` is a `CollectingBarrierStep` and `addV()` is a `SupplyingBarrierStep`.

`addE()` is like: "connect the vertices you queried to some user supplied set of vertices --> flatMap to those edges."
`addV()` is like: "if the query yields a result, add a vertex --> map to that vertex."

**Comment by dkuppitz** [comment]
What if I really want to add multiple vertices?

```groovy
g.V().has(label, "product").as("p").addV(label, "product-snapshot").
      addInE("snapshot", "p", "timestamp", System.currentTimeMillis()) // TODO: copy props
```

**Comment by dkuppitz** [comment]
To summarize, here's what we need:

#### Add Vertex

```groovy
traversal.addV(properties...) // which is equivalent to:
traversal.map {
    g.addVertex(properties) // can we access "g"?
}
```

#### Add Edge

```groovy
traversal.addInE(label, step, properties...) // which is equivalent to:
traversal.map {
    v = getElementAtNamedStep(step)
    v.addEdge(label, it.get(), properties)
}

traversal.addOutE(label, step, properties...) // which is equivalent to:
traversal.map {
    v = getElementAtNamedStep(step)
    it.get().addEdge(label, v, properties)
}

// is .addBothE() really necessary? It's somewhat special, since it requires .flatMap()
// instead of just .map(). I'd prefer to get rid of it.
traversal.addBothE(label, step, properties...) // which is equivalent to:
traversal.flatMap {
    v = getElementAtNamedStep(step)
    [v.addEdge(label, it.get(), properties), it.get().addEdge(label, v, properties)]
}
```

These steps are already available in `GraphTraversal`, but
* they don't allow to add properties and
* they emit a vertex (it's not clear which one - the in- or the out-vertex?)

#### Add / Update Property

```groovy
traversal.property(key, value) // which is equivalent to:
traversal.sideEffect {
    it.get().property(key, value)
}
```

Note that I chose `.sideEffect()` instead of `.map()`. Both would work, but I think `.sideEffect()` is the better choice for most use-cases.

#### Gotchas

As mentioned in a [previous comment](https://github.com/tinkerpop/tinkerpop3/issues/547#issuecomment-73552474), the `.add[In|Out|Both]E()` steps do not support a `weight` property, which was a nice feature in Faunus. Maybe that makes it worth to add more steps, e.g.:

```java
GraphTraversal<Vertex, Edge> addWeightedInE(String label, String step, String weightKey)
GraphTraversal<Vertex, Edge> addWeightedOutE(String label, String step, String weightKey)
GraphTraversal<Vertex, Edge> addWeightedBothE(String label, String step, String weightKey)
```

**Comment by okram** [comment]
This is done.
