### ISSUE TITLE
Do not propagate 'gremlin.graph'  config option via GraphFactory.open

### ISSUE THREAD

**Issue by asaf** [tinkerpop/tinkerpop3#548]
Hey,

Using `GraphFactory.open(Map)` with Titan works fine by this config:

```java
config.put("gremlin.graph", "com.thinkaurelius.titan.core.TitanFactory");
config.put("storage.titan.opt", "xyz");
TitanGraph graph = (TitanGraph) graphProvider.factory(config);
```

But Titan outputs exceptions such: ( and it's right because it's Titan :) )
```
java.lang.IllegalArgumentException: Unknown configuration element in namespace [root]: gremlin
```

I think we should avoid propagating the `gremlin.` config namespace to the underline factory method.

Thanks.

**Comment by spmallette** [comment]
I think that TinkerPop3 requires the config to be left as-is.  I don't remember the reason why but I know that we have a test that forces implementations to keep the original configuration:

https://github.com/tinkerpop/tinkerpop3/blob/be31bbdc208cb94bffd756bb45287a7d3a496107/gremlin-test/src/main/java/com/tinkerpop/gremlin/structure/GraphConstructionTest.java#L48

I think that vendors will need to account for this in their implementations a bit and filter as needed to avoid those kind of ugly warnings.

**Comment by asaf** [comment]
@spmallette I'm curious why :), not sure it's the best thing to push irrelevant configuration to vendor code but I guess there's a good reason for the test to be there in the first place,

I'll create a PR for Titan on its own repo,

Thanks.

**Comment by spmallette** [comment]
@okram do you remember the exact reason why we needed it this way?

**Comment by okram** [comment]
`graph.name`? -- we we could do reflection based graph creation in `GraphFactory`. You did it that way... ?

**Comment by spmallette** [comment]
right, but i thought there was a reason we didn't strip it from the configuration before passing it on to the underlying `Graph` after it was created.  we force implementations to preserve that configuration as-is.  i don't think it was accidentally done that way and i seem to remember it having something to do with giraph or the like.  if you don't remember anything specifically, that's cool.

**Comment by okram** [comment]
Perhaps Hadoop. Which configurations are ours and what configurations are Hadoop's... I think there are just too many configurations that we may have to account for that it might be best to just leave them in there.... ?

**Comment by spmallette** [comment]
i think we should just preserve the configuration as we are doing now.  titan is the only troublemaker in that it has strong validation of its configuration files and so anything in there that isn't titan related throws warnings.  i think vendors should just account for the one TP3 configuration in what is passed to them.  Hopefully that's not a big deal.
