### ISSUE TITLE
GraphSON does not preserve ID type

### ISSUE THREAD

**Issue by mhfrantz** [tinkerpop/tinkerpop3#557]
Using TinkerGraph, one can generate GraphSON, and when that GraphSON is read into a new graph, the ID of the elements can become Integer instead of Long.  After several "read, modify, write" cycles, this can eventually lead to a situation where duplicate ID's are detected when reading the GraphSON.

Here's a simple repro for the Gremlin console:
```groovy

toGraphSON = { g ->
    wbuilder = GraphSONWriter.build()
    writer = wbuilder.create()
    wstream = new ByteArrayOutputStream()
    writer.writeGraph(wstream, g)
    graphson = wstream.toString()
}

fromGraphSON = { graphson ->
    rbuilder = GraphSONReader.build()
    reader = rbuilder.create()
    rstream = new ByteArrayInputStream(graphson.getBytes())
    g = new TinkerGraph()
    reader.readGraph(rstream, g)
    g
}

roundTrip = fromGraphSON << toGraphSON

g1 = new TinkerGraph()
g1.addVertex()
g2 = roundTrip(g1)
g2.addVertex()
```
With the `g2` graph, one can see two vertices that appear to have ID `0`.
```
gremlin> g2.V()
==>v[0]
==>v[0]
gremlin> g2.V().group().by{ it.id }
==>[0:[v[0]], 0:[v[0]]]
gremlin> g2.V().filter{ it.get().id == 0 }
==>v[0]
==>v[0]
```
In fact, these are just Integer and Long versions of `0`.
```
gremlin> g2.V().group().by{ it.id.getClass().getName() }
==>[java.lang.Long:[v[0]], java.lang.Integer:[v[0]]]
```

**Comment by mhfrantz** [comment]
My temporary workaround for this is to patch TinkerHelper like so:
```java
    protected final synchronized static Object getNextId(final TinkerGraph graph) {
        final long nextId = Stream.generate(() -> (++graph.currentId)).filter(id -> !graph.vertices.containsKey(id) && !graph.edges.containsKey(id)).findAny().get();
        if (nextId <= Integer.MAX_VALUE)
            return (int) nextId;
        else
            return nextId;
    }
```

**Comment by spmallette** [comment]
By default GraphSON uses standard JSON typing and you therefore lose precision for numbers.  You should be able to preserve types by defining a custom `GraphSONMapper` and "embedding types":

```groovy
m = GraphSONMapper.build().embedTypes(true).create()
toGraphSON = { g ->
    wbuilder = GraphSONWriter.build().mapper(m)
    writer = wbuilder.create()
    wstream = new ByteArrayOutputStream()
    writer.writeGraph(wstream, g)
    graphson = wstream.toString()
}

fromGraphSON = { graphson ->
    rbuilder = GraphSONReader.build().mapper(m)
    reader = rbuilder.create()
    rstream = new ByteArrayInputStream(graphson.getBytes())
    g = new TinkerGraph()
    reader.readGraph(rstream, g)
    g
}

roundTrip = fromGraphSON << toGraphSON

g1 = new TinkerGraph()
g1.addVertex()
g2 = roundTrip(g1)
g2.addVertex()
```

This makes the GraphSON much more verbose, but at least types get preserved:

```text
gremlin> g2.V()
==>v[0]
==>v[1]
gremlin> g2.V().group().by{ it.id }
==>[0:[v[0]], 1:[v[1]]]
gremlin> g2.V().filter{ it.get().id == 0 }
==>v[0]
gremlin> g2.V().filter{ it.get().id == 1 }
==>v[1]
```

If you are on the JVM and don't need to have human readable data, you should prefer kryo to GraphSON. It will preserve types and be smaller and faster.

**Comment by mhfrantz** [comment]
Thanks for the info.  In this case, I do need human-readability and lossless encoding, so embedTypes is the trick.

**Comment by spmallette** [comment]
In some sense i'm glad you have this use case as it would be nice to hear if there are problems with how it works.  We've have done tests around it, but I feel like once something gets into the wild, it always finds a way to fail in a way not anticipated under development.  please let us know if there are problems with type embedding.
