### ISSUE TITLE
Gremlin Web Interface: "not a WebSocket handshake request: missing upgrade"

### ISSUE THREAD

**Issue by seanjames777** [tinkerpop/tinkerpop3#561]
When I attempt to access the Gremlin console through a web browser, all I see is an error message: not a WebSocket handshake request: missing upgrade.

I pulled and built the most recent version, as well as several previous versions going back a few weeks.

I am running bin/gremlish-server.sh. It appears to start correctly and says "Channel started at port 8182".

The issue occurs when opening http://localhost:8182 from Safari, Firefox, and Chrome on MacOSX Yosemite. It also occurs in Firefox on Ubuntu. So, I do not think this is a browser issue or an OS issue.

This appears to be an exception thrown by Netty: http://netty.io/4.0/xref/io/netty/handler/codec/http/websocketx/WebSocketServerHandshaker00.html

I'm not familiar with the codebase so I have not attempted to investigate the issue.

**Comment by spmallette** [comment]
Gremlin Server, as of right now and likely for GA, does not have a UI and by default is configured by default for websocket communication only.  The easiest way to talk to it when getting started is to simply remote your Gremlin to it via the Gremlin Console:

http://www.tinkerpop.com/docs/3.0.0-SNAPSHOT/#connecting-via-console

If you are interested in a REST interface then you need to make a slight configuration change:

http://www.tinkerpop.com/docs/3.0.0-SNAPSHOT/#_connecting_via_rest

You are the second person to get confused by this - so I suppose I need to make a change.  I will keep this open as I try to decide what that change will be.

**Comment by spmallette** [comment]
After some thought, I don't think I'm going to change anything here.  This issue will likely resolve itself in a different way should I implement a way to host multiple channelizers in a single Gremlin Server instance - that may yet be a feature.  Until then, the docs are pretty clear about what to expect when connecting to Gremlin Server - will rely on that to keep folks from going too far astray.
