### ISSUE TITLE
Generalize multi-label vertices in TP3

### ISSUE THREAD

**Issue by wsalembi** [tinkerpop/tinkerpop3#564]
Could the concept of multi-labels for vertices be added before the release of TP3? I think it is a powerful addition to the property graph model and it would certainly push graph vendors to implement this if it were part of the TP3 specification. Multi-labels allow to express multiple types or qualities for vertices, eg. a Person vertex could also have labels like Writer, Sportsman or Scientist, each of them can be associated with a particular set of vertex properties or edges.

This valuable feature currently only exists in Neo4J. (http://www.tinkerpop.com/docs/3.0.0-SNAPSHOT/#_multi_label). My proposal is to move the methods from Neo4jVertex to the Vertex interface and make it an opt-out feature for graph vendors that don't support this using graph.features().vertex().supportsMultiLabels() == false

**Comment by okram** [comment]
As it stands we want all Elements to have a single `label` -- edges and vertices. If you would like to work through a PR that redoes that work and the test suite, please feel free and we can review it and its ramifications.

**Comment by okram** [comment]
Will not do.

**Comment by wsalembi** [comment]
Unfortunate, because the Neo4j approach is really useful. 

I started a PR but didn't have the time to finish it yet. If this feature is refused, what would be the recommended way to implement this? A custom multi-property? Would the queries on this custom property be as fast as on the vertex label.
