### ISSUE TITLE
[proposal] Blow out the TraversalEngine concept

### ISSUE THREAD

**Issue by okram** [tinkerpop/tinkerpop3#565]
`TraversalEngine` is currently an enum of `STANDARD` (OLTP) and `COMPUTER` (OLAP). I think it needs to be an interface with the following methods.

```java
public enum Type { STANDARD, COMPUTER }
public void applyStrategies(final Traversal traversal)
public TraversalStrategies getTraversalStrategies()
public Graph getGraph()
```

`TinkerGraph` will provide `TinkerGraphComputerTraversalEngine`. This guy will:

```java
public void applyStrategies(final Traversal traversal) {
   this.getTraversalStrategies().apply(traversal);
   if(traversal.isRootTraversal()) 
     traversal.addStep(new ComputerResultStep(this.getGraph().compute().workers(workers).program(TraversalVertexProgram.class).traversal(traversal))))
}
```

When the `Traversal` is created (e.g. `g.V` or `v.out`), the `TraversalEngine` is provided to the traversal by, e.g., `TinkerGraph`, `TinkerVertex`. The user desired execution source is stated as such:

```java
tinkerGraph.setTraversalEngine(TinkerGraphComputerTraversalEngine.create().workers(2).build())  // OLAP
tinkerGraph.setTraversalEngine(StandardTraversalEngine.instance()) // OLTP
tinkerGraph.setTraversalEngine(GremlinServerTraversalEngine.create().host(1.2.3).port(23).remoteEngine(StandardTraversalEngine.instance()).build()) // GremlinServer
```

The first time a Traversal is `next()'d` or `hasNext()'d`, the `TraversalEngine` of the `Traversal` is executed. Note that `ComputeResultStep()` is added by `TinkerGraphComputerTraversalEngine` (see above). This means, at `next()` -- `TinkerGraphComputer` is submitted a `TraversalVertexProgram` and executed. The first `next()` is the result of the `TraversalVertexProgram`. This is sort of how we have it now, though `ComputerResultStep()` "wraps" the submitted traversal.

....there are still lots of holes -- e.g. do we need a `TraversalStrategiesCache`? How does `GremlinServer` come into play? Can different traversals within a traversal have different `TraversalEngines`....... 

anywho....just trying to get ideas out.

**Comment by okram** [comment]
I'm thinking that we need to make a distinction between "engine" and "algorithm".

  * "engine" is like typical iterator (OLTP), graph computer (OLAP), server (OLTP or OLAP), etc
  * "algorithm" is STANDARD (single machine) or COMPUTER (distributed).

As such, perhaps this is what the `TraversalEngine` interface looks like:

```java
public enum Algorithm { STANDARD, COMPUTER }
public void finalizeTraversal(final Traversal traversal)
public Algorithm getAlgorithm()
public Graph getGraph()
```

The `Traversal` is still responsible for its strategies based on ONLY TWO OPTIONS -- STANDARD or COMPUTER. That would be a hard constraint of TP3 -- you are either doing single machine iteration or distributed message passing....... ??????????????????????

```java
public StandardTraversalEngine implements TraversalEngine {
   private TraversalEngine.Algorithm algorithm = STANDARD;
   public void finalizeTraversal(final Traversal traversal) {} 
}
```

```java
public ComputerTraversalEngine implements TraversalEngine {
   private TraversalEngine.Algorithm algorithm = COMPUTER;
   public void finalizeTraversal(final Traversal traversal) {
      traversal.addStep(new ComputerResultStep(this.getGraph().computer().program(TraversalVertexProgram.class)));
   } 
}
```

Most vendors can get away with just `ComputerTraversalEngine.instance()` as they will only have one OLAP engine. However, if a vendor has multiple, they will need `ComputerTraversalEngine.build().computer(FulgoraGraphComputer.class).create()`.

```java
public ServerTraversalEngine implements TraversalEngine {
   private TraversalEngine.Algorithm algorithm = // dynamically set with build().create().
   public void finalizeTraversal(final Traversal traversal) {
      traversal.addStep(new GremlinServerResultStep(...);
   } 
}
```

With `GremlinServer` the user specifies the algorithm they want to have executed server side.

**Comment by mbroecheler** [comment]
I don't really understand the distinction. Doesn't OLTP always imply standard and OLAP computer? Can you elaborate?

**Comment by okram** [comment]
Finished. That was an insane amount of work and stress --- lots of factors came into play. What I have is 95% complete. With TraversalEngine now an interface, there are some API things I can make more succinct in Traversal... anywho....brutal.
