### ISSUE TITLE
:> Submit is stripping ' and " from submitted scripts.

### ISSUE THREAD

**Issue by okram** [tinkerpop/tinkerpop3#572]
```groovy
gremlin> :> g.V().out('knows')
Response iteration and serialization exceeded the configured threshold for request [RequestMessage{, requestId=6738b66b-6c86-48e0-b730-7c7d4c264faf, op='eval', processor='', args={gremlin=g.V().out( knows ), batchSize=64}}] - No such property: knows for class: Script3
Display stack trace? [yN]
```

This effects GremlinServer and Gremlin-Hadoop.

**Comment by spmallette** [comment]
it's related to this bug i reported - almost 100% sure of it:

https://jira.codehaus.org/browse/GROOVY-7290

May have to restate the problem to them to catch people's attention - or submit a PR to fix.  I will dig in and see if there is a workaround as well.

**Comment by spmallette** [comment]
posted a question on groovy-users to see how this can be resolved:

http://groovy.329449.n5.nabble.com/groovysh-and-command-parsing-td5722719.html

**Comment by spmallette** [comment]
I subclassed `Groovysh` and re-instituted the old style of command parsing.  Seems to work now:

```text
gremlin> :> TinkerFactory.createModern().V(1).out('knows')
==>v[2]
==>v[4]
gremlin> :> TinkerFactory.createModern().V(1).out("knows")
==>v[2]
==>v[4]
```

Will continue the discussion on what the future is for this issue in that groovy-users post above, but closing this for now.

**Comment by spmallette** [comment]
This issue was also created over in groovy to resolve this on the groovy-core side: 

https://jira.codehaus.org/browse/GROOVY-7311
