### ISSUE TITLE
TestSuite updates needed.

### ISSUE THREAD

**Issue by okram** [tinkerpop/tinkerpop3#573]
Right now we have two test classes for each test. For example:

  * `CountTest.ComputerTest`
  * `CountTest.StandardTest`

With `.submit(g.compute())` gone, the tests are identical. However, there are some traversals that don't execute on `GraphComputer`. As such, it would be good to have an annotation like:

`@ForceEngine(StandardTraversalEngine.class)`

Next, we need a way for traversal engine to be dynamically set. Right now we do this, which is ghetto:

https://github.com/apache/incubator-tinkerpop/blob/master/gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/GraphProvider.java#L101-L105

**Comment by spmallette** [comment]
Added two new annotations in `UseEngine` and `IgnoreEngine` in the test suite.  These tell the test process suite what engine to use for a test case and then for specific individual tests, which engine should be ignored if an engine isn't supported.  The process suite performs a certain amount of validation to ensure that the test cases are properly annotated.
