### ISSUE TITLE
groupCount variants

### ISSUE THREAD

**Issue by dkuppitz** [tinkerpop/tinkerpop3#574]
We need more variants for `groupCount`. Just pasting stuff from our previous conversation:

> GroupCountSideEffectStep (which is what is now)
> GroupCountReduceStep (which uses a barrier model)

**The problem:**

```groovy
gremlin> g.V().hasLabel("person").as("person").local(bothE().label().groupCount().cap()).as("relations").select()
==>[person:marko, relations:[created:1, knows:2]]
==>[person:vadas, relations:[created:1, knows:3]]
==>[person:josh, relations:[created:3, knows:4]]
==>[person:peter, relations:[created:4, knows:4]]
```

Looks good at the first sight, but the `groupCount()` numbers add up, which is not what we want in this case. A strategy could replace the `GroupCountSideEffectStep` with a `GroupCountReduceStep`, so that it would always be `groupCount()` for the user. But then you could also do this:

```groovy
g.V().hasLabel("person").local(bothE().label().groupCount()).cap()
```

Again, `groupCount()` is the last step within `local()`, but it may not be replaced by a `GroupCountReduceStep` as the `.cap()` is now part of parent traversal. Thus we probably need another name for the new step. Or we add something like `finalCap()` which returns the side-effect and resets it in the traverser's memory.

**Comment by dkuppitz** [comment]
What if `groupCount()` is the last step in the *outer* traversal? Do we want the `SideEffectCapStrategy` to append a `.cap()` or do we want to replace the `GroupCountSideEffectStep` with a `GroupCountReduceStep`?

**Comment by dkuppitz** [comment]
We want `.cap()`, because `GroupCountReduceStep` couldn't handle this:

```groovy
g.V().both().groupCount("m").both().groupCount("m")
```

**Comment by okram** [comment]
I was thinking --- I think we ONLY want `GroupCountReduceStep` at the end of local traversals as they do NOT have global sideEffects. This means that it would not work for `local()`, but that makes sense to me as `local()` (like `union()`,`branch()`,`choose()`) are "pass through" global traversals.

**Comment by dkuppitz** [comment]
> `g.V().hasLabel("person").as("p").local(bothE().label().groupCount()).as("r").select()`
> groupCount is a global sideEffect as all global traversals use global sideEffects.

Hence this is what we want:

```groovy
g.V().hasLabel("person").as("p").identity().as("r").select().by("name").
                                                             by(bothE().label().groupCount())
```

**Comment by okram** [comment]
This is done. Also done for `GroupStep`.
