### ISSUE TITLE
[proposal] Traversal steps provided by TP3 are the "only steps" a DSL can use.

### ISSUE THREAD

**Issue by okram** [tinkerpop/tinkerpop3#592]
Refactor `process/` API so its:

```
Traversal
  steps/
   filter/
   sideEffect/
   map/
  strategies/
   compilers/
   decorations/
GraphTraversal
   GraphTraversalSource
   DefaultGraphTraversal
```

**Comment by davidcrouch** [comment]
What do you mean exactly by "only steps"?   ....vendors cannot extend GraphTraversal?

**Comment by okram** [comment]
The "graph strategies" we will provide will be aware of the TP3 steps and optimize them accordingly. They do not know anything about user defined steps, as such, can not optimize them. Users can write their own steps, but TP3 strategies won't work for them.

**Comment by okram** [comment]
Done. That was a beast of a commit. However, now its very clear that Traversal and its Steps are the foundation of all DSLs.
